default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: studycircle

test:
  <<: *default
  database: studycircle_test

production:
  <<: *default
  database: studycircle_production
  password: <%= ENV["PRUEBA_DATABASE_PASSWORD"] %> # O cualquier variable que tengas definida para producción