# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

fing = University.find_or_create_by!(name: 'Facultad de Ingeniería', location: 'Montevideo')
ingcomp = Career.find_or_create_by!(name: 'Ingeniería en Computación', university: fing)
ingsist = Career.find_or_create_by!(name: 'Ingeniería en Sistemas de Comunicacion', university: fing)

subjects = [
  { name: 'Programación 1', career: ingcomp },
  { name: 'Programación 2', career: ingcomp },
  { name: 'Programación 3', career: ingcomp },
  { name: 'Programación 4', career: ingcomp },
  { name: 'Lógica', career: ingcomp },
  { name: 'Computación 1', career: ingcomp },
  { name: 'Arquitectura de Computadoras', career: ingcomp },
  { name: 'Aportes epistémicos del pensamiento computacional a la educación en ciencias', career: ingcomp },
  { name: 'Conceptos de Lenguajes de Programación', career: ingcomp },
  { name: 'Técnicas avanzadas de Modelado y Simulación', career: ingcomp },
  { name: 'Taller de Iniciación a los Sistemas Ciber-Físicos', career: ingcomp },
  { name: 'Redes Neuronales para Lenguaje Natural', career: ingcomp },
  { name: 'Taller de Datos', career: ingcomp },
  { name: 'Espacio Grados 1 y 2', career: ingcomp },
  { name: 'Informática Médica', career: ingcomp },
  { name: 'Ciencia de Datos y Lenguaje Natural', career: ingcomp },
  { name: 'Taller de Minería de Procesos de Negocio', career: ingcomp },
  { name: 'Experimentando con métodos ágiles de software', career: ingcomp },
  { name: 'Optimización Continua y Aplicaciones', career: ingcomp },
  { name: 'Introducción a las Bases de Datos', career: ingcomp },
  { name: 'Módulos de Taller y Extensión (PLN)', career: ingcomp },
  { name: 'Aspectos Avanzados y Complemento de Arquitectura de Computadoras', career: ingcomp },
  { name: 'Aspectos Avanzados de Redes de Computadoras', career: ingcomp },
  { name: 'Análisis y Diseño de Algoritmos Distribuidos en Redes', career: ingcomp },
  { name: 'Algoritmos Evolutivos', career: ingcomp },
  { name: 'Álgebra Lineal Numérica', career: ingcomp },
  { name: 'Combinatoria Analítica', career: ingcomp },
  { name: 'Aprendizaje Automático', career: ingcomp },
  { name: 'Análisis de datos en redes complejas', career: ingcomp },
  { name: 'Análisis semántico de lenguaje natural', career: ingcomp },
  { name: 'Administración y Seguridad de Sistemas', career: ingcomp },
  { name: 'Aplicaciones de la Teoría de la Información al Procesamiento de Imágenes', career: ingcomp },
  { name: 'Bases de datos no relacionales', career: ingcomp },
  { name: 'Combinatoria Analítica y Aplicaciones', career: ingcomp },
  { name: 'Calidad de Datos e Información', career: ingcomp },
  { name: 'Compresión de Datos sin Pérdida', career: ingcomp },
  { name: 'Curvas Elípticas en Criptografía', career: ingcomp },
  { name: 'Construcción Formal de Programas en Teoría de Tipos', career: ingcomp },
  { name: 'Computación Gráfica Avanzada', career: ingcomp },
  { name: 'Introducción a la Computación Gráfica', career: ingcomp },
  { name: 'Diseño de Compiladores', career: ingcomp },
  { name: 'Complejidad Computacional', career: ingcomp },
  { name: 'Criptografía', career: ingcomp },
  { name: 'Didáctica de Algoritmos y Estructuras de Datos', career: ingcomp },
  { name: 'Diseño de interfaces gráficas de usuario', career: ingcomp },
  { name: 'Diseño Topológico de Redes', career: ingcomp },
  { name: 'Fundamentos de Bases de Datos', career: ingcomp },
  { name: 'Ejecución ágil guiada por hitos', career: ingcomp },
  { name: 'Enfoque de Pulsos para solución de problemas de caminos más cortos con restricciones', career: ingcomp },
  { name: 'Epistemología genética y aplicaciones a la didáctica de la informática', career: ingcomp },
  { name: 'Estándares e Interoperabilidad en Salud', career: ingcomp },
  { name: 'Simulación a Eventos Discretos', career: ingcomp },
  { name: 'Experimentos con la Web Semántica', career: ingcomp },
  { name: 'Formación de Formadores en Robótica Educativa', career: ingcomp },
  { name: 'Fundamentos de Ingeniería de Software', career: ingcomp },
  { name: 'Fundamentos de Programación Entera', career: ingcomp },
  { name: 'Fundamentos de Programación y Robótica', career: ingcomp },
  { name: 'Fundamentos de la robótica autónoma', career: ingcomp },
  { name: 'Formación en robótica educativa para educadores', career: ingcomp },
  { name: 'Fundamentos de la Seguridad Informática', career: ingcomp },
  { name: 'Fundamentos de la web semántica', career: ingcomp },
  { name: 'Generación aleatoria en criptografía', career: ingcomp },
  { name: 'Programación masivamente paralela en procesadores gráficos', career: ingcomp },
  { name: 'Gramáticas Formales para el Lenguaje Natural', career: ingcomp },
  { name: 'Sistemas de Información para el Análisis de Grandes Volúmenes de Datos', career: ingcomp },
  { name: 'Gestión y Análisis de Datos Espaciales', career: ingcomp },
  { name: 'Computación de alta performance', career: ingcomp },
  { name: 'Integración de Datos', career: ingcomp },
  { name: 'Introducción a la Didáctica de la Informática', career: ingcomp },
  { name: 'Introducción a la Investigación, E-Learning y Semantic Web', career: ingcomp },
  { name: 'Introducción a la Investigación de Operaciones', career: ingcomp },
  { name: 'Introducción a la Ingeniería de Software', career: ingcomp },
  { name: 'Sistemas de Información en Salud', career: ingcomp },
  { name: 'Ingeniería de Software Empírica', career: ingcomp },
  { name: 'Introducción al Middleware', career: ingcomp },
  { name: 'Introducción al Procesamiento de Lenguaje Natural', career: ingcomp },
  { name: 'Investigación de Operaciones y Gestión de Riesgos', career: ingcomp },
  { name: 'Introducción a las Redes de Computadoras', career: ingcomp },
  { name: 'Introducción a Robotic Operating System', career: ingcomp },
  { name: 'Ingeniería de Software basada en evidencia', career: ingcomp },
  { name: 'Lógica de Descripciones', career: ingcomp },
  { name: 'Métodos de Aprendizaje Automático', career: ingcomp },
  { name: 'Métodos ágiles para equipos de software de alto desempeño', career: ingcomp },
  { name: 'Modelos Combinatorios de Confiabilidad en Redes', career: ingcomp },
  { name: 'Modelado Cuantitativo para Problemas de Producción', career: ingcomp },
  { name: 'Matemática discreta usando ISetl', career: ingcomp },
  { name: 'Manejo práctico de las enfermedades crónicas con el apoyo de la informática y la telemedicina', career: ingcomp },
  { name: 'Métodos Eficientes de Simulación para la Estimación de Confiabilidad en Redes', career: ingcomp },
  { name: 'Métodos de Monte Carlo', career: ingcomp },
  { name: 'Modelado y Optimización', career: ingcomp },
  { name: 'Metaheurísticas y optimización sobre redes', career: ingcomp },
  { name: 'Herramientas de Visualización', career: ingcomp },
  { name: 'El Negocio del Software', career: ingcomp },
  { name: 'Nomenclatura clínica y consulta médica', career: ingcomp },
  { name: 'Optimización de Problemas de Producción', career: ingcomp },
  { name: 'Optimización bajo Incertidumbre', career: ingcomp },
  { name: 'Programación Lógica', career: ingcomp },
  { name: 'Profesión en ingeniería de software', career: ingcomp },
  { name: 'Pensamiento de Diseño: Teoría y práctica', career: ingcomp },
  { name: 'Programación Funcional Avanzada', career: ingcomp },
  { name: 'Proyecto de Ingeniería de Software', career: ingcomp },
  { name: 'Planificación y Seguimiento de Proyectos de Software', career: ingcomp },
  { name: 'Programa de Mejoramiento de la Experiencia Educativa', career: ingcomp },
  { name: 'Programación en Processing para Entornos Multimedia', career: ingcomp },
  { name: 'Principios y fundamentos del Proceso Personal de Software', career: ingcomp },
  { name: 'Programación Funcional', career: ingcomp },
  { name: 'Proyecto de Grado', career: ingcomp },
  { name: 'Prueba Lógica', career: ingcomp },
  { name: 'Robótica basada en Comportamientos', career: ingcomp },
  { name: 'Taller de Radio Definida por Software', career: ingcomp },
  { name: 'Redes de Computadoras', career: ingcomp },
  { name: 'Enrutamiento en la Internet del Futuro', career: ingcomp },
  { name: 'Robótica educativa', career: ingcomp },
  { name: 'Robótica Embebida', career: ingcomp },
  { name: 'Robótica de servicio', career: ingcomp },
  { name: 'Relaciones Personales en Ingeniería de Software', career: ingcomp },
  { name: 'Introducción a los Sistemas de Información Geográfica', career: ingcomp },
  { name: 'Sistemas embebidos e Internet de las cosas', career: ingcomp },
  { name: 'Sistemas Operativos', career: ingcomp },
  { name: 'Teoría, Algoritmos y Aplicaciones de Gestión Logística', career: ingcomp },
  { name: 'Técnicas Avanzadas en Gestión de Sistemas de Información', career: ingcomp },
  { name: 'Taller de GPGPU', career: ingcomp },
  { name: 'Taller de Seguridad Informática', career: ingcomp },
  { name: 'Taller de Gestión y Tecnologías de Procesos de Negocios', career: ingcomp },
  { name: 'Temas avanzados en códigos para corrección de errores', career: ingcomp },
  { name: 'Códigos para Corrección de Errores', career: ingcomp },
  { name: 'Técnicas de descomposición en Programación Matemática', career: ingcomp },
  { name: 'Teoría de la Computación', career: ingcomp },
  { name: 'Teoría de Lenguajes', career: ingcomp },
  { name: 'Taller De Evaluación De Tecnologías De La Información', career: ingcomp },
  { name: 'Teoría de Juegos Evolutivos', career: ingcomp },
  { name: 'Taller de Programación', career: ingcomp },
  { name: 'Herramientas para el diseño y análisis de redes de transporte urbano de pasajeros', career: ingcomp },
  { name: 'Taller de Robótica Educativa Con El Robot Butiá', career: ingcomp },
  { name: 'Taller de Sistemas Ciber-Físicos', career: ingcomp },
  { name: 'Taller de Sistemas Empresariales', career: ingcomp },
  { name: 'Taller de Sistemas de Información 1', career: ingcomp },
  { name: 'Taller de Sistemas de Información Geográficos Empresariales', career: ingcomp },
  { name: 'Taller de Sistemas Operativos', career: ingcomp },
  { name: 'Taller de Lenguajes y Tecnologías de la Web Semántica', career: ingcomp },
  { name: 'Taller de verificación de software', career: ingcomp },
  { name: 'Recuperación de Información y Recomendaciones en la Web', career: ingcomp },
  { name: 'Mejora de interfaz de accesibilidad XEvents', career: ingcomp },
  { name: 'Taller de Representación y Comunicación Gráfica', career: ingcomp },
  { name: 'Introducción al Derecho', career: ingcomp },
  { name: 'Políticas Científicas en Informática y Computación', career: ingcomp },
  { name: 'Ciencia, Tecnología y Sociedad', career: ingcomp },
  { name: 'Economía', career: ingcomp },
  { name: 'Taller de Administración para Ingeniería Civil', career: ingcomp },
  { name: 'Representación Gráfica para las Industrias de Procesos', career: ingcomp },
  { name: 'Diseño y Montaje de las Industrias de Procesos', career: ingcomp },
  { name: 'Práctica de Administración para Ingenieros', career: ingcomp },
  { name: 'Administración General para Ingenieros', career: ingcomp },
  { name: 'Legislación y Relaciones Industriales', career: ingcomp },
  { name: 'Ingeniería Legal', career: ingcomp },
  { name: 'Organización para Ingenieros', career: ingcomp },
  { name: 'Introducción a la Administración para Ingenieros', career: ingcomp },
  { name: 'Metalurgia de Transformación', career: ingcomp },
  { name: 'Materiales y Ensayos', career: ingcomp },
  { name: 'Metalurgia Física', career: ingcomp },
  { name: 'Introducción a la Ciencia de los Materiales', career: ingcomp },
  { name: 'Envases Poliméricos para la industria alimenticia', career: ingcomp },
  { name: 'Caminos y Calles 1', career: ingcomp },
  { name: 'Caminos y Calles 2', career: ingcomp },
  { name: 'Costos', career: ingcomp },
  { name: 'Elasticidad', career: ingcomp },
  { name: 'Elementos de Geología para la Planificación Territorial', career: ingcomp },
  { name: 'Elementos Finitos', career: ingcomp },
  { name: 'Estructuras Laminares', career: ingcomp },
  { name: 'Estructuras de Acero', career: ingcomp },
  { name: 'Estructuras de Madera', career: ingcomp },
  { name: 'Geología de Ingeniería', career: ingcomp },
  { name: 'Hormigón Estructural 1', career: ingcomp },
  { name: 'Hormigón Estructural 2', career: ingcomp },
  { name: 'Hormigón Estructural 3', career: ingcomp },
  { name: 'Introducción a la Mecánica de Suelos', career: ingcomp },
  { name: 'Introducción a la Construcción', career: ingcomp },
  { name: 'Introducción a la Corrosión del Hormigón Armado', career: ingcomp },
  { name: 'Introducción al Transporte', career: ingcomp },
  { name: 'Laboratorio de Mecánica de Suelos', career: ingcomp },
  { name: 'Laboratorio de Resistencia de Materiales', career: ingcomp },
  { name: 'Laboratorio de Tecnología del Hormigón', career: ingcomp },
  { name: 'Mampostería Estructural', career: ingcomp },
  { name: 'Máquinas y Equipos para Transporte', career: ingcomp },
  { name: 'Mecánica Estructural', career: ingcomp },
  { name: 'Métodos Computacionales Aplicados al Cálculo Estructural', career: ingcomp },
  { name: 'Pasantía en Ingeniería Civil', career: ingcomp },
  { name: 'Patología de las Estructuras', career: ingcomp },
  { name: 'Procedimientos de Construcción para Estructuras', career: ingcomp },
  { name: 'Procedimientos de Construcción para Obras Viales y de Suelos', career: ingcomp },
  { name: 'Proyecto de Investigación e Innovación en Ingeniería Estructural', career: ingcomp },
  { name: 'Proyecto Estructural 1', career: ingcomp },
  { name: 'Proyecto Estructural 2', career: ingcomp },
  { name: 'Proyecto Estructural Anual (PEA)', career: ingcomp },
  { name: 'Proyecto Transporte 1', career: ingcomp },
  { name: 'Proyecto Transporte 2', career: ingcomp },
  { name: 'Proyecto, Planificación y Construcción de Obras 1', career: ingcomp },
  { name: 'Proyecto, Planificación y Construcción de Obras 2', career: ingcomp },
  { name: 'Puentes 2024', career: ingcomp },
  { name: 'Puentes: Diseño y Construcción', career: ingcomp },
  { name: 'Resistencia de Materiales 1', career: ingcomp },
  { name: 'Resistencia de Materiales 2', career: ingcomp },
  { name: 'Seguridad en la Construcción', career: ingcomp },
  { name: 'Taller de Ingeniería Civil: Implementación y Calibración del Equipo de Desgaste para Superficies de Hormigón', career: ingcomp },
  { name: 'Taller de Introducción a la Metodología BIM', career: ingcomp },
  { name: 'Tecnología del Hormigón', career: ingcomp },
  { name: 'Taller de Evaluación de Pavimentos', career: ingcomp },
  { name: 'Transporte Aéreo', career: ingcomp },
  { name: 'Transporte Ferroviario', career: ingcomp },
  { name: 'Transporte Fluvial y Marítimo', career: ingcomp },
  { name: 'Transporte por Carretera', career: ingcomp },
  { name: 'Transporte Urbano', career: ingcomp },
  { name: 'Física 1', career: ingcomp },
  { name: 'Física 2', career: ingcomp },
  { name: 'Física 3', career: ingcomp },
  { name: 'Mecánica Newtoniana', career: ingcomp },
  { name: 'Física Experimental 2', career: ingcomp },
  { name: 'Física Experimental 3', career: ingcomp },
  { name: 'Vibraciones y Ondas', career: ingcomp },
  { name: 'Electromagnetismo', career: ingcomp },
  { name: 'Física Térmica', career: ingcomp },
  { name: 'Laboratorio de Medidas Físicas', career: ingcomp },
  { name: 'Antenas y Propagación', career: ingcomp },
  { name: 'Comunicaciones Digitales', career: ingcomp },
  { name: 'Digitalización y Codificación Multimedia 2024', career: ingcomp },
  { name: 'Diseño de Circuitos para Instrumentación Electrónica', career: ingcomp },
  { name: 'Diseño Lógico 2', career: ingcomp },
  { name: 'Electrónica Avanzada 2', career: ingcomp },
  { name: 'Electrónica de Potencia', career: ingcomp },
  { name: 'Electrónica Fundamental', career: ingcomp },
  { name: 'Electrotécnica', career: ingcomp },
  { name: 'Electrotécnica 1', career: ingcomp },
  { name: 'Estimación y Predicción en Series Temporales', career: ingcomp },
  { name: 'Generación de Energía Eléctrica', career: ingcomp },
  { name: 'Gestión Integrada de Redes y Servicios de Telecomunicaciones', career: ingcomp },
  { name: 'Imágenes Médicas: Adquisición, Instrumentación y Gestión', career: ingcomp },
  { name: 'Internado de Ingeniería Biomédica', career: ingcomp },
  { name: 'Introducción a la Teoría de la Información', career: ingcomp },
  { name: 'Introducción a los Microprocesadores', career: ingcomp },
  { name: 'Introducción a los Sistemas de Protección de Sistemas Eléctricos de Potencia', career: ingcomp },
  { name: 'Introducción al Control Industrial', career: ingcomp },
  { name: 'Medidas Eléctricas', career: ingcomp },
  { name: 'Microbit', career: ingcomp },
  { name: 'Programación para Ingeniería Eléctrica', career: ingcomp },
  { name: 'Proyecto de Instalaciones Eléctricas', career: ingcomp },
  { name: 'Redes de Datos 2', career: ingcomp },
  { name: 'Redes Eléctricas', career: ingcomp },
  { name: 'Seminario de Ingeniería Biomédica', career: ingcomp },
  { name: 'Señales y Sistemas', career: ingcomp },
  { name: 'Simulación de Sistemas de Energía Eléctrica', career: ingcomp },
  { name: 'Sistemas de Control en Tiempo Discreto', career: ingcomp },
  { name: 'Sistemas Embebidos para Tiempo Real', career: ingcomp },
  { name: 'Subestaciones de Media Tensión', career: ingcomp },
  { name: 'Taller de Aprendizaje Automático', career: ingcomp },
  { name: 'Taller de Introducción a la Ingeniería Eléctrica', career: ingcomp },
  { name: 'Taller de Máquinas Eléctricas', career: ingcomp },
  { name: 'Técnicas de Ensayo de Materiales y Equipamiento en Alta Tensión', career: ingcomp },
  { name: 'Tecnologías de Redes y Servicios de Telecomunicaciones', career: ingcomp },
  { name: 'Tecnologías para la Internet de las Cosas', career: ingcomp },
  { name: 'Transformadores de Medida y Protección', career: ingcomp },
  { name: 'Tratamiento de Imágenes por Computadora', career: ingcomp },
  { name: 'Diseño de Transformadores de Distribución y Potencia', career: ingcomp },
  { name: 'Diseño de Redes Inalámbricas de Clase Empresarial', career: ingcomp },
  { name: 'Vehículos Híbridos, Eléctricos y a Hidrógeno (VHE&H)', career: ingcomp },
  { name: 'Seminario de Mercados Eléctricos', career: ingcomp },
  { name: 'Análisis 3D del Movimiento de la Rodilla para Rehabilitación, Evaluación Perioperatoria y Medicina del Deporte', career: ingcomp },
  { name: 'Física de la Luz', career: ingcomp },
  { name: 'Generación Eólica', career: ingcomp },
  { name: 'Seminario en Redes Neuronales Basadas en la Física (PINNs)', career: ingcomp },
  { name: 'Taller de Procesamiento de Audio y Video con Pure Data/Gem', career: ingcomp },
  { name: 'Técnicas de Sensado Remoto para Aplicaciones Urbanas y Ambientales', career: ingcomp },
  { name: 'Redes Ópticas', career: ingcomp },
  { name: 'Distribución y Aplicaciones Multimedia 2024', career: ingcomp },
  { name: 'Seminario sobre Encuentros entre Arte y Tecnologías', career: ingcomp },
  { name: 'Introducción a la Programación y Análisis de Texto con R', career: ingcomp },
  { name: 'Alumbrado LED', career: ingcomp },
  { name: 'Aprendizaje Automático para Datos en Grafos', career: ingcomp },
  { name: 'Aprendizaje Profundo para Visión Artificial', career: ingcomp },
  { name: 'Captura de la Bandera', career: ingcomp },
  { name: 'Circuitos de Radiofrecuencia', career: ingcomp },
  { name: 'Complemento de Temas Avanzados en Sistemas Inalámbricos', career: ingcomp },
  { name: 'Comunicaciones Inalámbricas', career: ingcomp },
  { name: 'Conceptos Avanzados sobre Protección de Sistemas Eléctricos de Potencia', career: ingcomp },
  { name: 'Diseño de Antenas', career: ingcomp },
  { name: 'Diseño de Circuitos Integrados', career: ingcomp },
  { name: 'Diseño de Circuitos Integrados CMOS Analógicos y Mixto', career: ingcomp },
  { name: 'Diseño de Sistemas Médicos Implantables Activos', career: ingcomp },
  { name: 'Diseño Digital de Bajo Consumo', career: ingcomp },
  { name: 'Diseño Lógico', career: ingcomp },
  { name: 'Eficiencia Energética', career: ingcomp },
  { name: 'Electrónica Avanzada 1', career: ingcomp },
  { name: 'Electrotécnica 2', career: ingcomp },
  { name: 'Ensayos Eléctricos y Equipamiento de Media Tensión', career: ingcomp },
  { name: 'Fabricación y Medida de Antenas', career: ingcomp },
  { name: 'Fundamentos de Aprendizaje Automático', career: ingcomp },
  { name: 'Ingeniería Biomédica', career: ingcomp },
  { name: 'Ingeniería Clínica', career: ingcomp },
  { name: 'Instalaciones Eléctricas', career: ingcomp },
  { name: 'Introducción a la Teoría de Control', career: ingcomp },
  { name: 'Controladores Lógicos Programables', career: ingcomp },
  { name: 'Máquinas Eléctricas', career: ingcomp },
  { name: 'Monografías de Medidas Eléctricas', career: ingcomp },
  { name: 'Planificación de la Expansión de la Generación de Sistemas Eléctricos', career: ingcomp },
  { name: 'Proyecto de Instalaciones Eléctricas BT y MT', career: ingcomp },
  { name: 'Taller Fourier', career: ingcomp },
  { name: 'Red de Acceso', career: ingcomp },
  { name: 'Redes de Datos 1', career: ingcomp },
  { name: 'Redes de Sensores Inalámbricos', career: ingcomp },
  { name: 'Seminario de Iniciación a la Investigación', career: ingcomp },
  { name: 'Señales Aleatorias y Modulación', career: ingcomp },
  { name: 'Sistemas y Control', career: ingcomp },
  { name: 'Taller de Introducción a la Ingeniería Eléctrica (2s)', career: ingcomp },
  { name: 'Taller Laboratorio de Electrónica de Potencia', career: ingcomp },
  { name: 'Técnicas de Ensayo de Materiales y Equipamiento en Alta Tensión', career: ingcomp },
  { name: 'Técnicas Experimentales de Ultrasonido', career: ingcomp },
  { name: 'Tecnología de Servicios Audiovisuales', career: ingcomp },
  { name: 'Temas Avanzados en Sistemas Inalámbricos', career: ingcomp },
  { name: 'Transporte de Energía Eléctrica', career: ingcomp },
  { name: 'Calidad de Energía: Conceptos y Herramientas para su Abordaje', career: ingcomp },
  { name: 'Protección contra Descargas Atmosféricas', career: ingcomp },
  { name: 'Teoría de Circuitos', career: ingcomp },
  { name: 'Energía Solar Fotovoltaica', career: ingcomp },
  { name: 'Ingeniería Cardiovascular del Laboratorio a la Clínica', career: ingcomp },
  { name: 'Tecnologías, Operación y Aplicación del Almacenamiento de Energía en Sistemas Eléctricos', career: ingcomp },
  { name: 'Procesamiento Digital de Señales de Audio', career: ingcomp },
  { name: 'Costos para Ingeniería', career: ingcomp },
  { name: 'Modelado de sistemas Mecánicos Empleando el Método de los Elementos Finitos', career: ingcomp },
  { name: 'Comportamiento Mecánico de Materiales 2', career: ingcomp },
  { name: 'Mecánica Aplicada', career: ingcomp },
  { name: 'Transporte Industrial', career: ingcomp },
  { name: 'Sistemas Oleohidráulicos y Neumáticos', career: ingcomp },
  { name: 'Transferencia de Calor 1', career: ingcomp },
  { name: 'Generadores de Vapor', career: ingcomp },
  { name: 'Evaluación Económica y Financiera de Proyectos de Inversión', career: ingcomp },
  { name: 'Control de Calidad', career: ingcomp },
  { name: 'Tiempos y Métodos', career: ingcomp },
  { name: 'Introducción a la Ingeniería Naval', career: ingcomp },
  { name: 'Introducción a la Ingeniería de Producción', career: ingcomp },
  { name: 'Taller 4: Mejora de la competitividad', career: ingcomp },
  { name: 'Dinámica de Máquinas y Vibraciones', career: ingcomp },
  { name: 'Elementos de Navegación', career: ingcomp },
  { name: 'Teoría de Restricciones', career: ingcomp },
  { name: 'Refrigeración', career: ingcomp },
  { name: 'Transferencia de Calor 2', career: ingcomp },
  { name: 'Gestión de la Calidad', career: ingcomp },
  { name: 'Instrumentación Industrial', career: ingcomp },
  { name: 'Fundamentos de Robótica Industrial', career: ingcomp },
  { name: 'Planeamiento Estratégico y Estrategia Competitiva', career: ingcomp },
  { name: 'Comportamiento Mecánico de Materiales 1', career: ingcomp },
  { name: 'Elementos de Máquinas', career: ingcomp },
  { name: 'Mantenimiento de Buques', career: ingcomp },
  { name: 'Estructuras de Buques', career: ingcomp },
  { name: 'Energía 1', career: ingcomp },
  { name: 'Generación de Energía en Plantas de Vapor y Gas', career: ingcomp },
  { name: 'Teoría de Máquinas y Mecanismos', career: ingcomp },
  { name: 'Motores de Combustión Interna', career: ingcomp },
  { name: 'Administración de Operaciones', career: ingcomp },
  { name: 'Gestión de Recursos Humanos', career: ingcomp },
  { name: 'Proyecto Ingeniería Industrial Mecánica', career: ingcomp },
  { name: 'Elementos de Gestión Logística', career: ingcomp },
  { name: 'Gestión de Mantenimiento', career: ingcomp },
  { name: 'Diseño de procesos químicos', career: ingcomp },
  { name: 'Termodinámica Aplicada a la Ingeniería de Procesos', career: ingcomp },
  { name: 'Fenómenos de Transporte en Ingeniería de Procesos', career: ingcomp },
  { name: 'Tecnología y Servicios Industriales 1', career: ingcomp },
  { name: 'Transferencia de Calor y Masa 2', career: ingcomp },
  { name: 'Ingeniería de las Reacciones Químicas 1', career: ingcomp },
  { name: 'Diseño de Procesos Químicos', career: ingcomp },
  { name: 'Ingeniería Bioquímica', career: ingcomp },
  { name: 'Introducción a la Prevención de Riesgos Laborales', career: ingcomp },
  { name: 'Gestión de Laboratorios', career: ingcomp },
  { name: 'Gestión de Procesos en la Industria', career: ingcomp },
  { name: 'Tratamiento de Efluentes y Residuos Sólidos', career: ingcomp },
  { name: 'Energía aplicada a la industria 2024', career: ingcomp },
  { name: 'Diseño de procesos electroquímicos', career: ingcomp },
  { name: 'Introducción a la Ingeniería de Procesos', career: ingcomp },
  { name: 'Introducción a la Ingeniería en Alimentos', career: ingcomp },
  { name: 'Medidas Eléctricas en Ingeniería de Procesos', career: ingcomp },
  { name: 'Introducción a la Ingeniería Química', career: ingcomp },
  { name: 'Ingeniería Ambiental para la Industria de Procesos', career: ingcomp },
  { name: 'Fluidodinámica', career: ingcomp },
  { name: 'Transferencia de Calor y Masa 1', career: ingcomp },
  { name: 'Introducción a la Ingeniería Bioquímica', career: ingcomp },
  { name: 'Ingeniería de las Reacciones Químicas 2', career: ingcomp },
  { name: 'Tecnología y Servicios Industriales 2', career: ingcomp },
  { name: 'Higiene y Servicios Industriales', career: ingcomp },
  { name: 'Fundamentos de la Producción de Celulosa y Papel', career: ingcomp },
  { name: 'Control de la Corrosión', career: ingcomp },
  { name: 'Dinámica y Control de Procesos', career: ingcomp },
  { name: 'Matemática Inicial', career: ingcomp },
  { name: 'Cálculo Diferencial e Integral en una Variable', career: ingcomp },
  { name: 'Geometría y Álgebra Lineal 1', career: ingcomp },
  { name: 'Matemática Discreta 1', career: ingcomp },
  { name: 'Cálculo Diferencial e Integral en Varias Variables', career: ingcomp },
  { name: 'Geometría y Álgebra Lineal 2', career: ingcomp },
  { name: 'Matemática Discreta 2', career: ingcomp },
  { name: 'Cálculo Vectorial', career: ingcomp },
  { name: 'Probabilidad y Estadística', career: ingcomp },
  { name: 'Funciones de Variable Compleja', career: ingcomp },
  { name: 'Fundamentos de Optimización', career: ingcomp },
  { name: 'Ecuaciones Diferenciales 2', career: ingcomp },
  { name: 'Introducción a las Ecuaciones Diferenciales', career: ingcomp },
  { name: 'Métodos Numéricos', career: ingcomp },
  { name: 'Aplicaciones del Álgebra Lineal', career: ingcomp },
  { name: 'Modelos Estadísticos para la Regresión y la Clasificación', career: ingcomp },
  { name: 'Soluciones Basadas en la Naturaleza para Ambientes Costeros', career: ingcomp },
  { name: 'Modelización Numérica de la Atmósfera', career: ingcomp },
  { name: 'Taller de Técnicas de Medición en Hidrología e Hidráulica', career: ingcomp },
  { name: 'Física de la Atmósfera', career: ingcomp },
  { name: 'Estadística Aplicada en Ingeniería Hidráulica y Ambiental', career: ingcomp },
  { name: 'Obras Hidráulicas', career: ingcomp },
  { name: 'Impulsores del cambio en océanos y costas', career: ingcomp },
  { name: 'Elementos de Meteorología', career: ingcomp },
  { name: 'Hidráulica fluvial y marítima', career: ingcomp },
  { name: 'Diseño Hidrológico', career: ingcomp },
  { name: 'Hidrodinámica Naval', career: ingcomp },
  { name: 'Calidad de Aguas', career: ingcomp },
  { name: 'Gestión de Calidad Ambiental', career: ingcomp },
  { name: 'Proyecto de Hidráulica Ambiental', career: ingcomp },
  { name: 'Taller de Introducción a las Ciencias de la Atmósfera', career: ingcomp },
  { name: 'Evaluación de Impacto Ambiental', career: ingcomp },
  { name: 'Hidráulica Marítima y Costera', career: ingcomp },
  { name: 'Introducción a la Evaluación y Gestión Ambiental', career: ingcomp },
  { name: 'Teoría del Buque', career: ingcomp },
  { name: 'Elementos de Ingeniería Ambiental', career: ingcomp },
  { name: 'Potabilización de Aguas', career: ingcomp },
  { name: 'Introducción a la Ingeniería Sanitaria', career: ingcomp },
  { name: 'Diseño de Redes de Conducción en Ingeniería Sanitaria', career: ingcomp },
  { name: 'Represas y Canales', career: ingcomp },
  { name: 'Módulo de Extensión en Ingeniería Ambiental', career: ingcomp },
  { name: 'Laboratorio de Calidad de Aguas', career: ingcomp },
  { name: 'Hidrología Avanzada I', career: ingcomp },
  { name: 'Sistemas de Conducción en Ingeniería Sanitaria', career: ingcomp },
  { name: 'Ejercicios de Ingeniería Sanitaria', career: ingcomp },
  { name: 'Tratamiento de efluentes', career: ingcomp },
  { name: 'Mecánica de los Fluidos', career: ingcomp },
  { name: 'Elementos de Mecánica de los Fluidos', career: ingcomp },
  { name: 'Máquinas para fluidos 1', career: ingcomp },
  { name: 'Máquinas para fluidos 2', career: ingcomp },
  { name: 'Hidrología e Hidráulica Aplicadas', career: ingcomp },
  { name: 'Hidrología Avanzada II', career: ingcomp }
]

subjects.each do |subject|
  Subject.find_or_create_by!({ name: subject[:name], career: subject[:career] })
end

# Creo dos usuarios tutores, este va a tener asociados temas (disponibilidades)
user_1 = User.find_or_create_by!({
  name: "John Doe",
  email: "john.doe@example.com",
  uid: "123456789",
  description: "Tutor especializado en matemáticas.",
  image_url: "https://i.pinimg.com/550x/74/bb/34/74bb340ffe87e31837a04a538f1bbc10.jpg",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
  }
)

user_2 = User.find_or_initialize_by(email: "jane.doe@example.com")
user_2.assign_attributes({
  name: "Jane Doe",
  uid: "123451789",
  description: "Tutor especializado en algo.",
  image_url: "https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
  }
)
user_2.save!
# Este usuario va a ser estudiante
user_3 = User.find_or_create_by!({
  name: "Juan Pablo",
  email: "juan.pablo@example.com",
  uid: "123456782",
  description: "Estudiante.",
  image_url: "https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
})

programacion1_id = Subject.find_by(name: "Programación 1").id
logica_id = Subject.find_by(name: "Lógica").id
# Topics Creation
# Programación 1 - subject_id = 1
begin
Topic.find_or_create_by!([
  { name: "Introducción a la Programación", description: "Conceptos básicos de programación.", subject_id: programacion1_id },
  { name: "Estructuras de Control", description: "Condicionales y bucles.", subject_id: programacion1_id },
  { name: "Funciones", description: "Cómo escribir funciones y modularizar código.", subject_id: programacion1_id },
  { name: "Manejo de Errores", description: "Técnicas para el manejo de errores en programación.", subject_id: programacion1_id },
  { name: "Programación Orientada a Objetos", description: "Fundamentos de POO.", subject_id: programacion1_id }
])
rescue
end

# Lógica - subject_id = 5
Topic.find_or_create_by!([
  { name: "Proposiciones Lógicas", description: "Introducción a la lógica proposicional.", subject_id: logica_id },
  { name: "Tablas de Verdad", description: "Uso de tablas de verdad para evaluar expresiones.", subject_id: logica_id },
  { name: "Tautologías y Contradicciones", description: "Estudio de tautologías y contradicciones lógicas.", subject_id: logica_id },
  { name: "Lógica de Predicados", description: "Introducción a la lógica de predicados.", subject_id: logica_id },
  { name: "Cuantificadores", description: "Cuantificadores existenciales y universales.", subject_id: logica_id }
])

# Creation of Availabilities for two topics of subject_1 for the user created
topics = Topic.where(subject_id: programacion1_id)
topics.each do |topic|
  AvailabilityTutor.find_or_create_by!({
    user_id: user_1.id,
    topic_id: topic.id
})
end

topics = Topic.where(subject_id: logica_id)
topics.each do |topic|
  availability = AvailabilityTutor.find_or_create_by!({
    user_id: user_2.id,
    topic_id: topic.id
  })
end
