# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

fing = University.find_or_create_by!(name: 'Facultad de Ingeniería', location: 'Montevideo')

ingcomp = Career.find_or_create_by!(name: 'Ingeniería en Computación', university: fing)
ingsist = Career.find_or_create_by!(name: 'Ingeniería en Sistemas de Comunicacion', university: fing)
civil = Career.find_or_create_by!(name: 'Ingeniería Civil', university: fing)
alimentos = Career.find_or_create_by!(name: 'Ingeniería de Alimentos', university: fing)
produccion = Career.find_or_create_by!(name: 'Ingeniería de Producción', university: fing)
electrica = Career.find_or_create_by!(name: 'Ingeniería Eléctrica', university: fing)
agrimensura = Career.find_or_create_by!(name: 'Ingeniería en Agrimensura', university: fing)
fisico_matematica = Career.find_or_create_by!(name: 'Ingeniería Físico-Matemática', university: fing)
forestal = Career.find_or_create_by!(name: 'Ingeniería Forestal (Tacuarembó)', university: fing)
industrial_mecanica = Career.find_or_create_by!(name: 'Ingeniería Industrial Mecánica', university: fing)
naval = Career.find_or_create_by!(name: 'Ingeniería Naval', university: fing)
quimica = Career.find_or_create_by!(name: 'Ingeniería Química', university: fing)
atmosfera = Career.find_or_create_by!(name: 'Lic. en Ciencias de la Atmósfera', university: fing)
computacion = Career.find_or_create_by!(name: 'Lic. en Computación', university: fing)
biologica = Career.find_or_create_by!(name: 'Lic. en Ingeniería Biológica', university: fing)
recursos_hidricos = Career.find_or_create_by!(name: 'Lic. en Recursos Hídricos y Riego (RN-Salto)', university: fing)

subjects = [
  # Licenciatura en Computación
  { name: 'Bases de Datos', career: computacion },
  { name: 'Sistemas de Información', career: computacion },
  { name: 'Talleres de Sistemas de Información', career: computacion },
  { name: 'Principios de Redes', career: computacion },
  { name: 'Diseño de Redes', career: computacion },
  { name: 'Algoritmos Distribuidos', career: computacion },
  { name: 'Seguridad Informática', career: computacion },
  { name: 'Sistemas Operativos', career: computacion },
  { name: 'Simulación', career: computacion },
  { name: 'Modelado y Optimización', career: computacion },
  { name: 'Deducción', career: computacion },
  { name: 'Inferencia', career: computacion },
  { name: 'Reconocimiento de Patrones', career: computacion },
  { name: 'Resolución de Problemas', career: computacion },
  { name: 'Robótica', career: computacion },
  { name: 'Procesamiento del Lenguaje Natural', career: computacion },
  { name: 'Introducción a la Ingeniería de Software', career: computacion },
  { name: 'Proyecto de Ingeniería de Software', career: computacion },
  { name: 'Cálculo 1', career: computacion },
  { name: 'Cálculo Diferencial e Integral en una Variable', career: computacion },
  { name: 'Cálculo 2', career: computacion },
  { name: 'Cálculo Diferencial e Integral en Varias Variables', career: computacion },
  { name: 'Álgebra Lineal', career: computacion },
  { name: 'Geometría y Álgebra Lineal 1', career: computacion },
  { name: 'Geometría y Álgebra Lineal 2', career: computacion },
  { name: 'Matemática Discreta 1', career: computacion },
  { name: 'Matemática Discreta 2', career: computacion },
  { name: 'Lógica', career: computacion },
  { name: 'Lógica y Computación', career: computacion },
  { name: 'Programación 1', career: computacion },
  { name: 'Programación 2', career: computacion },
  { name: 'Programación 3', career: computacion },
  { name: 'Programación 4', career: computacion },
  { name: 'Teoría de Lenguajes', career: computacion },
  { name: 'Introducción a la Arquitectura de Computadores', career: computacion },
  { name: 'Arquitectura de Computadoras 1', career: computacion },
  { name: 'Arquitectura de Computadoras', career: computacion },
  { name: 'Aspectos Básicos de Redes de Computadoras', career: computacion },
  { name: 'Redes de Computadoras', career: computacion },
  { name: 'Fundamentos de Base de Datos', career: computacion },
  { name: 'Control de Calidad', career: computacion },
  { name: 'Introducción a la Administración para Ingeniería', career: computacion },
  { name: 'Administración General para Ingeniería', career: computacion },
  { name: 'Práctica de Administración para Ingeniería', career: computacion },
  { name: 'Taller de Programación', career: computacion },
  { name: 'Introducción a la Programación Funcional', career: computacion },
  { name: 'Introducción a la Programación Lógica', career: computacion },
  { name: 'Programación Lógica', career: computacion },
  { name: 'Programación Funcional Avanzada', career: computacion },
  { name: 'Introducción a la Programación Genérica', career: computacion },
  { name: 'Construcción Formal de Programas en Teoría de Tipos', career: computacion },
  { name: 'Verificación de Modelos', career: computacion },
  { name: 'Teoría de la Computación', career: computacion },
  { name: 'Diseño de Compiladores', career: computacion },
  { name: 'Fundamentos de Seguridad Informática', career: computacion },
  { name: 'Taller de Seguridad Informática', career: computacion },
  { name: 'Actividad Integradora A', career: computacion },
  { name: 'Actividad Integradora B', career: computacion },
  { name: 'Tesis de Licenciatura en Computación', career: computacion },
  { name: 'Introducción a la Computación Gráfica', career: computacion },
  { name: 'Interacción Persona Computadora', career: computacion },
  { name: 'Tratamiento de Imágenes por Computadora', career: computacion },
  { name: 'Aplicaciones de la Teoría de la Información al Procesamiento de Imágenes', career: computacion },
  { name: 'Aprendizaje Profundo para Visión Artificial', career: computacion },
  { name: 'Computación Gráfica Avanzada', career: computacion },
  { name: 'Métodos Monte Carlo', career: computacion },
  { name: 'Álgebra Lineal Numérica', career: computacion },
  { name: 'Métodos Numéricos', career: computacion },
  { name: 'Computación de Propósito General en Unidades de Procesamiento Gráfico', career: computacion },
  { name: 'Taller de GPGPU', career: computacion },
  { name: 'Aprendizaje Automático', career: computacion },
  { name: 'Computación de Alta Performance', career: computacion },
  { name: 'Introducción a los Sistemas de Información Geográfica', career: computacion },
  { name: 'Algoritmos Evolutivos', career: computacion },
  # Licenciatura en Recursos Hídricos y Riego
  { name: 'Cálculo 1', career: recursos_hidricos },
  { name: 'Cálculo 2', career: recursos_hidricos },
  { name: 'Geometría y álgebra lineal 1', career: recursos_hidricos },
  { name: 'Geometría y álgebra lineal 2', career: recursos_hidricos },
  { name: 'Introducción a la Probabilidad y la Estadística', career: recursos_hidricos },
  { name: 'Cálculo vectorial', career: recursos_hidricos },
  { name: 'Física 1', career: recursos_hidricos },
  { name: 'Física 2', career: recursos_hidricos },
  { name: 'Física 3', career: recursos_hidricos },
  { name: 'Física Experimental 1', career: recursos_hidricos },
  { name: 'Computación y métodos numéricos', career: recursos_hidricos },
  { name: 'Química del agua', career: recursos_hidricos },
  { name: 'Instalaciones hidráulicas a presión', career: recursos_hidricos },
  { name: 'Mecánica de fluidos', career: recursos_hidricos },
  { name: 'Hidráulica de conducciones a superficie libre', career: recursos_hidricos },
  { name: 'Hidrología 11', career: recursos_hidricos },
  { name: 'Hidrología subterránea', career: recursos_hidricos },
  { name: 'Sistemas de conducción y drenaje urbano', career: recursos_hidricos },
  { name: 'Obras hidráulicas', career: recursos_hidricos },
  { name: 'Modelos hidrológicos', career: recursos_hidricos },
  { name: 'Geofísica general', career: recursos_hidricos },
  { name: 'Geología', career: recursos_hidricos },
  { name: 'Geotécnica', career: recursos_hidricos },
  { name: 'Métodos geofísicos aplicados', career: recursos_hidricos },
  { name: 'Topografía y Sistemas de Información Geográfica', career: recursos_hidricos },
  { name: 'Agrometeorología', career: recursos_hidricos },
  { name: 'Agroefluentes y saneamiento para pequeñas comunidades', career: recursos_hidricos },
  { name: 'Edafología', career: recursos_hidricos },
  { name: 'Introducción a la actividad agropecuaria', career: recursos_hidricos },
  { name: 'Sistemas de riego y drenaje 1', career: recursos_hidricos },
  { name: 'Sistemas de riego y drenaje 2', career: recursos_hidricos },
  { name: 'Medio ambiente y calidad del agua', career: recursos_hidricos },
  { name: 'Normativa y legislación del agua', career: recursos_hidricos },
  { name: 'Taller de diseño', career: recursos_hidricos },
  # Licenciatura en Ingeniería Biológica
  { name: 'Álgebra lineal', career: biologica },
  { name: 'Cálculo diferencial e integral en una y varias variables', career: biologica },
  { name: 'Funciones de variable compleja', career: biologica },
  { name: 'Ecuaciones diferenciales', career: biologica },
  { name: 'Probabilidad y estadística', career: biologica },
  { name: 'Transformadas integrales', career: biologica },
  { name: 'Métodos numéricos', career: biologica },
  { name: 'Optimización', career: biologica },
  { name: 'Magnitudes y propagación de errores', career: biologica },
  { name: 'Mecánica', career: biologica },
  { name: 'Termodinámica', career: biologica },
  { name: 'Electromagnetismo', career: biologica },
  { name: 'Física moderna', career: biologica },
  { name: 'Biofísica', career: biologica },
  { name: 'Química orgánica', career: biologica },
  { name: 'Bioquímica', career: biologica },
  { name: 'Fisicoquímica', career: biologica },
  { name: 'Anatomía', career: biologica },
  { name: 'Fisiología', career: biologica },
  { name: 'Biología celular y molecular', career: biologica },
  { name: 'Patología', career: biologica },
  { name: 'Biología computacional', career: biologica },
  { name: 'Programación estructurada', career: biologica },
  { name: 'Programación de sistemas de tiempo real', career: biologica },
  { name: 'Programación orientada a objetos', career: biologica },
  { name: 'Arquitectura de Sistemas', career: biologica },
  { name: 'Algoritmos y estructuras de datos', career: biologica },
  { name: 'Sistemas Operativos', career: biologica },
  # Licenciatura en Ciencias de la Atmósfera
  { name: 'Cálculo 1', career: atmosfera },
  { name: 'Cálculo 2', career: atmosfera },
  { name: 'Cálculo 3', career: atmosfera },
  { name: 'Geometría y Álgebra Lineal 1', career: atmosfera },
  { name: 'Geometría y Álgebra Lineal 2', career: atmosfera },
  { name: 'Ecuaciones Diferenciales', career: atmosfera },
  { name: 'Cálculo Diferencial e Integral 1', career: atmosfera },
  { name: 'Cálculo Diferencial e Integral 2', career: atmosfera },
  { name: 'Cálculo Vectorial y Análisis Complejo', career: atmosfera },
  { name: 'Álgebra Lineal I', career: atmosfera },
  { name: 'Álgebra Lineal II', career: atmosfera },
  { name: 'Introducción a las Ecuaciones Diferenciales', career: atmosfera },
  { name: 'Física General 1', career: atmosfera },
  { name: 'Física General 2', career: atmosfera },
  { name: 'Mecánica Newtoniana', career: atmosfera },
  { name: 'Física Térmica', career: atmosfera },
  { name: 'Mec. de Sist. y Fenómenos Ondulatorios', career: atmosfera },
  { name: 'Electromagnetismo', career: atmosfera },
  { name: 'Física Moderna', career: atmosfera },
  { name: 'Teoría Electromagnética', career: atmosfera },
  { name: 'Física I', career: atmosfera },
  { name: 'Física II', career: atmosfera },
  { name: 'Mecánica Clásica', career: atmosfera },
  { name: 'Termodinámica', career: atmosfera },
  { name: 'Ondas', career: atmosfera },
  { name: 'Electromagnetismo', career: atmosfera },
  { name: 'Física Moderna', career: atmosfera },
  { name: 'Mecánica Estadística', career: atmosfera },
  { name: 'Física no lineal', career: atmosfera },
  { name: 'Elementos de Mecánica de los Fluidos', career: atmosfera },
  { name: 'Mecánica de los Fluidos', career: atmosfera },
  { name: 'Elementos de Meteorología y Clima', career: atmosfera },
  { name: 'Meteorología Dinámica y Taller Sinóptico', career: atmosfera },
  { name: 'Complementos en Meteorología', career: atmosfera },
  { name: 'Taller de Pronóstico', career: atmosfera },
  { name: 'Hidráulica Marítima', career: atmosfera },
  { name: 'Física de la Materia II', career: atmosfera },
  { name: 'Inestabilidad de Fluidos', career: atmosfera },
  { name: 'Met. Exp. para el estudio de Fluidos', career: atmosfera },
  { name: 'Probabilidades y Estadística', career: atmosfera },
  { name: 'Análisis de Datos Climáticos', career: atmosfera },
  { name: 'Tratamiento Estadístico de señales', career: atmosfera },
  { name: 'Tratamiento de señales', career: atmosfera },
  { name: 'Computación 1', career: atmosfera },
  { name: 'Métodos Numéricos', career: atmosfera },
  { name: 'Modelación Numérica de la Atmósfera', career: atmosfera },
  { name: 'Física Computacional', career: atmosfera },
  { name: 'Taller de Expresión', career: atmosfera },
  { name: 'Taller de Introducción a la Meteorología', career: atmosfera },
  { name: 'Laboratorio 1', career: atmosfera },
  { name: 'Trabajo Especial', career: atmosfera },
  { name: 'Taller I', career: atmosfera },
  { name: 'Taller II', career: atmosfera },
  { name: 'Hidrología Aplicada', career: atmosfera },
  { name: 'Hidrología Estadística', career: atmosfera },
  { name: 'Hidrología Subterránea', career: atmosfera },
  { name: 'Elementos de Ingeniería Ambiental', career: atmosfera },
  { name: 'Módulo Corrosión Atm. y Contaminación', career: atmosfera },
  { name: 'Agrometeorología', career: atmosfera },
  { name: 'Sistemas de Información Geográfico', career: atmosfera },
  { name: 'Percepción Remota', career: atmosfera },
  { name: 'Hidrología', career: atmosfera },
  { name: 'Oceanografia', career: atmosfera },
  { name: 'Tecnología y Sociedad', career: atmosfera },
  { name: 'Economía', career: atmosfera },
  { name: 'Ciencia y desarrollo', career: atmosfera },
  { name: 'Epistemología', career: atmosfera },
  { name: 'Historia de la Ciencia', career: atmosfera },
  { name: 'Principios de Química General', career: atmosfera },
  { name: 'Química 1', career: atmosfera },
  { name: 'Química General', career: atmosfera },
  { name: 'Química de la Atmósfera y Polución', career: atmosfera },
  # Ing Quimica
  { name: 'Álgebra lineal', career: quimica },
  { name: 'Cálculo diferencial e integral en una variable', career: quimica },
  { name: 'Cálculo diferencial e integral en varias variables', career: quimica },
  { name: 'Cálculo vectorial', career: quimica },
  { name: 'Ecuaciones diferenciales ordinarias y en derivadas parciales', career: quimica },
  { name: 'Probabilidad y estadística', career: quimica },
  { name: 'Cálculo numérico', career: quimica },
  { name: 'Optimización', career: quimica },
  { name: 'Mecánica', career: quimica },
  { name: 'Electromagnetismo', career: quimica },
  { name: 'Termodinámica', career: quimica },
  { name: 'Magnitudes y Propagación de Errores', career: quimica },
  { name: 'Estequiometría', career: quimica },
  { name: 'Estructura atómica', career: quimica },
  { name: 'Periodicidad', career: quimica },
  { name: 'Enlace químico', career: quimica },
  { name: 'Métodos de análisis químico', career: quimica },
  { name: 'Reacciones químicas', career: quimica },
  { name: 'Estructura, reactividad y propiedades de compuestos orgánicos', career: quimica },
  { name: 'Sistemas fisicoquímicos en equilibrio', career: quimica },
  { name: 'Termoquímica', career: quimica },
  { name: 'Tópicos de química inorgánica', career: quimica },
  { name: 'Electroquímica', career: quimica },
  { name: 'Tópicos de química avanzada', career: quimica },
  { name: 'Química de materiales', career: quimica },
  { name: 'Química ambiental', career: quimica },
  { name: 'Bioquímica', career: quimica },
  { name: 'Microbiología', career: quimica },
  { name: 'Balances de materia y energía', career: quimica },
  { name: 'Análisis dimensional', career: quimica },
  { name: 'Termodinámica aplicada', career: quimica },
  { name: 'Fenómenos de transporte', career: quimica },
  { name: 'Fluidodinámica', career: quimica },
  { name: 'Transferencia de calor', career: quimica },
  { name: 'Transferencia de materia', career: quimica },
  { name: 'Ingeniería de las reacciones químicas', career: quimica },
  { name: 'Diseño de procesos', career: quimica },
  { name: 'Dinámica y control de procesos', career: quimica },
  { name: 'Resistencia de materiales', career: quimica },
  { name: 'Elementos de máquinas', career: quimica },
  { name: 'Sistemas mecánicos', career: quimica },
  { name: 'Teoría de circuitos', career: quimica },
  { name: 'Electrotecnia básica', career: quimica },
  { name: 'Máquinas eléctricas', career: quimica },
  { name: 'Costos y administración', career: quimica },
  { name: 'Gestión de calidad', career: quimica },
  { name: 'Gestión empresarial', career: quimica },
  { name: 'Seguridad y salud en el trabajo', career: quimica },
  { name: 'Legislación y gestión humana', career: quimica },
  { name: 'Diseño y representación gráfica', career: quimica },
  # Ing Naval
  { name: 'Cálculo I', career: naval },
  { name: 'Cálculo II', career: naval },
  { name: 'Cálculo III', career: naval },
  { name: 'Geometría y Algebra Lineal I', career: naval },
  { name: 'Geometría y Algebra Lineal II', career: naval },
  { name: 'Probabilidad y Estadística', career: naval },
  { name: 'Ecs. Diferenciales y Series de Fourier', career: naval },
  { name: 'Física General I', career: naval },
  { name: 'Física General II', career: naval },
  { name: 'Mecánica I', career: naval },
  { name: 'Mecánica II', career: naval },
  { name: 'Mecánica de Fluídos', career: naval },
  { name: 'Mecánica de Sólidos', career: naval },
  { name: 'Termodinámica', career: naval },
  { name: 'Electromagnetismo', career: naval },
  { name: 'Termodinámica Aplicada I', career: naval },
  { name: 'Termodinámica Aplicada II', career: naval },
  { name: 'Fluídos Máquinas I', career: naval },
  { name: 'Fluídos Máquinas II', career: naval },
  { name: 'Energía I (Combustión)', career: naval },
  { name: 'Energía II (Turbina de Vapor)', career: naval },
  { name: 'Energía III (Planificación)', career: naval },
  { name: 'Generadores de Vapor', career: naval },
  { name: 'Refrigeración', career: naval },
  { name: 'Motores de Combustión Interna', career: naval },
  { name: 'Ciencia de Materiales', career: naval },
  { name: 'Metalurgia Física I', career: naval },
  { name: 'Metalurgia de Transformación', career: naval },
  { name: 'Comp. Mecánico de Materiales', career: naval },
  { name: 'Teoría de Máquinas y Mecanismos', career: naval },
  { name: 'Elementos de Máquinas', career: naval },
  { name: 'Dinámica de Máquinas y Vibraciones', career: naval },
  { name: 'Teoría de Diseño', career: naval },
  { name: 'Materiales Compuestos', career: naval },
  { name: 'Trabajos Esp. en Metalurgia', career: naval },
  { name: 'Control de Calidad', career: naval },
  { name: 'Introducción a la Ing. Industrial', career: naval },
  { name: 'Costos para Ingeniería', career: naval },
  { name: 'Comercialización', career: naval },
  { name: 'Gestión de Mantenimiento', career: naval },
  { name: 'Gestión de Calidad', career: naval },
  { name: 'Gestión de Proyectos', career: naval },
  { name: 'Higiene y Seguridad Industrial', career: naval },
  { name: 'Administración de Operaciones', career: naval },
  { name: 'Control e Instrumentación Industrial', career: naval },
  { name: 'Control I', career: naval },
  { name: 'Introducción a la Electrotecnia', career: naval },
  { name: 'Instalaciones Eléctricas', career: naval },
  { name: 'Conversión Electromecánica', career: naval },
  { name: 'Máquinas Eléctricas II', career: naval },
  { name: 'Máquinas Eléctricas III', career: naval },
  { name: 'Computación I', career: naval },
  { name: 'Cálculo Numérico', career: naval },
  { name: 'Economía Política', career: naval },
  { name: 'Tecnología y Sociedad', career: naval },
  { name: 'Expresión Gráfica', career: naval },
  { name: 'Arquitectura Naval 1', career: naval },
  { name: 'Arquitectura Naval 2', career: naval },
  { name: 'Maquinaria Naval 1', career: naval },
  { name: 'Maquinaria Naval 2', career: naval },
  { name: 'Alistamiento de Buques 1', career: naval },
  { name: 'Alistamiento de Buques 2', career: naval },
  { name: 'Construcción Naval 1', career: naval },
  { name: 'Construcción Naval 2', career: naval },
  { name: 'Reparaciones Navales', career: naval },
  # Ing Industrial Mecanica
  { name: 'Cálculo I', career: industrial_mecanica },
  { name: 'Cálculo II', career: industrial_mecanica },
  { name: 'Cálculo III', career: industrial_mecanica },
  { name: 'Geometría y Algebra Lineal I', career: industrial_mecanica },
  { name: 'Geometría y Algebra Lineal II', career: industrial_mecanica },
  { name: 'Probabilidad y Estadística', career: industrial_mecanica },
  { name: 'Ecs. Diferenciales y Series de Fourier', career: industrial_mecanica },
  { name: 'Física General I', career: industrial_mecanica },
  { name: 'Física General II', career: industrial_mecanica },
  { name: 'Mecánica I', career: industrial_mecanica },
  { name: 'Mecánica II', career: industrial_mecanica },
  { name: 'Mecánica de Fluídos', career: industrial_mecanica },
  { name: 'Mecánica de Sólidos', career: industrial_mecanica },
  { name: 'Termodinámica', career: industrial_mecanica },
  { name: 'Electromagnetismo', career: industrial_mecanica },
  { name: 'Termodinámica Aplicada I', career: industrial_mecanica },
  { name: 'Termodinámica Aplicada II', career: industrial_mecanica },
  { name: 'Fluídos Máquinas I', career: industrial_mecanica },
  { name: 'Fluídos Máquinas II', career: industrial_mecanica },
  { name: 'Energía I (Combustión)', career: industrial_mecanica },
  { name: 'Energía II (Turbina de Vapor)', career: industrial_mecanica },
  { name: 'Energía III (Planificación)', career: industrial_mecanica },
  { name: 'Generadores de Vapor', career: industrial_mecanica },
  { name: 'Refrigeración', career: industrial_mecanica },
  { name: 'Ciencia de Materiales', career: industrial_mecanica },
  { name: 'Metalurgia Física I', career: industrial_mecanica },
  { name: 'Metalurgia de Transformación', career: industrial_mecanica },
  { name: 'Comp. Mecánico de Materiales', career: industrial_mecanica },
  { name: 'Teoría de Máquinas y Mecanismos', career: industrial_mecanica },
  { name: 'Elementos de Máquinas', career: industrial_mecanica },
  { name: 'Dinámica de Máquinas y Vibraciones', career: industrial_mecanica },
  { name: 'Teoría de Diseño', career: industrial_mecanica },
  { name: 'Materiales Compuestos', career: industrial_mecanica },
  { name: 'Control de Calidad', career: industrial_mecanica },
  { name: 'Introducción a la Ing. Industrial', career: industrial_mecanica },
  { name: 'Costos para Ingeniería', career: industrial_mecanica },
  { name: 'Comercialización', career: industrial_mecanica },
  { name: 'Gestión de Mantenimiento', career: industrial_mecanica },
  { name: 'Gestión de Calidad', career: industrial_mecanica },
  { name: 'Gestión de Proyectos', career: industrial_mecanica },
  { name: 'Higiene y Seguridad Industrial', career: industrial_mecanica },
  { name: 'Administración de Operaciones', career: industrial_mecanica },
  { name: 'Control e Instrumentación Industrial', career: industrial_mecanica },
  { name: 'Control I', career: industrial_mecanica },
  { name: 'Introducción a la Electrotecnia', career: industrial_mecanica },
  { name: 'Instalaciones Eléctricas', career: industrial_mecanica },
  { name: 'Conversión Electromecánica', career: industrial_mecanica },
  { name: 'Máquinas Eléctricas II', career: industrial_mecanica },
  { name: 'Máquinas Eléctricas III', career: industrial_mecanica },
  { name: 'Química General', career: industrial_mecanica },
  { name: 'Corrosión Industrial', career: industrial_mecanica },
  { name: 'Computación I', career: industrial_mecanica },
  { name: 'Cálculo Numérico', career: industrial_mecanica },
  { name: 'Economía Política', career: industrial_mecanica },
  { name: 'Tecnología y Sociedad', career: industrial_mecanica },
  { name: 'Expresión Gráfica', career: industrial_mecanica },
  # Ing forestal
  { name: 'Introducción a las ciencias forestales', career: forestal },
  { name: 'Cálculo 1', career: forestal },
  { name: 'Geometría y álgebra lineal', career: forestal },
  { name: 'Principios de química para Ing Forestal', career: forestal },
  { name: 'Biología general', career: forestal },
  { name: 'Geología y recursos naturales', career: forestal },
  { name: 'Estructura y Fisiología Celular', career: forestal },
  { name: 'Cálculo 2', career: forestal },
  { name: 'Botánica, Anatomía y Fisiología Vegetal', career: forestal },
  { name: 'Estadística I', career: forestal },
  { name: 'Física 1', career: forestal },
  { name: 'Silvicultura Básica', career: forestal },
  { name: 'Computación 1', career: forestal },
  { name: 'Paisaje', career: forestal },
  { name: 'Botánica', career: forestal },
  { name: 'Silvicultura Aplicada', career: forestal },
  { name: 'Física Térmica / Termodinámica', career: forestal },
  { name: 'Fluidos y Energía', career: forestal },
  { name: 'Química orgánica 1', career: forestal },
  { name: 'Electrotecnia, Instrumentación y Control', career: forestal },
  { name: 'Taller de introducción a la investigación de operaciones', career: forestal },
  { name: 'Bioquímica', career: forestal },
  { name: 'Tecnología de la Madera', career: forestal },
  { name: 'Política y Legislación', career: forestal },
  { name: 'Física 3', career: forestal },
  { name: 'Química orgánica 2', career: forestal },
  { name: 'Genética vegetal', career: forestal },
  { name: 'Fisiología vegetal', career: forestal },
  { name: 'Pasantía', career: forestal },
  { name: 'Trabajo Final', career: forestal },
  { name: 'Taller ciclo hidrológico forestal', career: forestal },
  { name: 'Taller temas ecología forestal', career: forestal },
  { name: 'Química de la madera', career: forestal },
  { name: 'Entomología general', career: forestal },
  { name: 'Política y legislación forestal', career: forestal },
  { name: 'Materiales', career: forestal },
  { name: 'Electrotecnica 1', career: forestal },
  { name: 'Introducción a la economía de los recursos naturales', career: forestal },
  { name: 'Estadística II', career: forestal },
  { name: 'Microbiología', career: forestal },
  { name: 'Suelos 1', career: forestal },
  { name: 'Introducción a la genética cuantitativa y de poblaciones', career: forestal },
  { name: 'Silvicultura de las plantaciones', career: forestal },
  { name: 'Anatomía de la madera', career: forestal },
  { name: 'Entomología forestal', career: forestal },
  { name: 'Dendrometría', career: forestal },
  { name: 'Mecánica de los fluidos', career: forestal },
  { name: 'Economía y gestión en la actividad forestal', career: forestal },
  { name: 'Comportamiento mecánico de materiales', career: forestal },
  { name: 'Gestión y control de calidad en la actividad forestal', career: forestal },
  { name: 'Dasometría', career: forestal },
  { name: 'Instrumentación y control', career: forestal },
  { name: 'Producción de celulosa y papel', career: forestal },
  { name: 'Deterioro y preservación de la madera', career: forestal },
  { name: 'Manejo de bosque nativo', career: forestal },
  { name: 'Evaluación de impacto ambiental', career: forestal },
  { name: 'Aserrado – Procesos de corte en madera', career: forestal },
  { name: 'Transferencia de Calor y Masa', career: forestal },
  { name: 'Maquinaria para Operaciones forestales', career: forestal },
  { name: 'Taller de datos espaciales y sistemas de información geográfica', career: forestal },
  { name: 'Cosecha forestal', career: forestal },
  { name: 'Trabajo final IF', career: forestal },
  { name: 'Dibujo Técnico', career: forestal },
  { name: 'Logistica Industrial', career: forestal },
  { name: 'Ecofisiología de leñosas', career: forestal },
  { name: 'Gestión Forestal Avanzada', career: forestal },
  { name: 'Mejoramiento Genético Forestal', career: forestal },
  { name: 'Taller de cartas geográficas', career: forestal },
  { name: 'Combustión', career: forestal },
  { name: 'Encolados y Tableros', career: forestal },
  # Ing Fisico Matematica
  { name: 'Cálculo diferencial e integral en una variable', career: fisico_matematica },
  { name: 'Física 1', career: fisico_matematica },
  { name: 'Principios de Química General', career: fisico_matematica },
  { name: 'Cálculo diferencial e integral en varias variables', career: fisico_matematica },
  { name: 'Física 2', career: fisico_matematica },
  { name: 'Geometría y álgebra lineal 1', career: fisico_matematica },
  { name: 'Física 3', career: fisico_matematica },
  { name: 'Física experimental 1', career: fisico_matematica },
  { name: 'Geometría y álgebra lineal 2', career: fisico_matematica },
  { name: 'Física experimental 2', career: fisico_matematica },
  { name: 'Cálculo vectorial', career: fisico_matematica },
  { name: 'Introducción a las ecuaciones diferenciales', career: fisico_matematica },
  { name: 'Física térmica', career: fisico_matematica },
  { name: 'Probabilidad y estadística', career: fisico_matematica },
  { name: 'Mecánica Newtoniana', career: fisico_matematica },
  { name: 'Computación científica', career: fisico_matematica },
  { name: 'Programación 1', career: fisico_matematica },
  { name: 'Programación 2', career: fisico_matematica },
  { name: 'Métodos numéricos', career: fisico_matematica },
  { name: 'Introducción a la investigación de operaciones', career: fisico_matematica },
  { name: 'Transferencia de calor y masa 1', career: fisico_matematica },
  { name: 'Fenómenos de transporte en ingeniería de procesos', career: fisico_matematica },
  { name: 'Introducción a la ingeniería de procesos', career: fisico_matematica },
  { name: 'Fluidodinámica', career: fisico_matematica },
  { name: 'Dinámica y control de procesos', career: fisico_matematica },
  { name: 'Taller inicial', career: fisico_matematica },
  { name: 'Taller IFM', career: fisico_matematica },
  { name: 'Pasantía', career: fisico_matematica },
  { name: 'Proyecto', career: fisico_matematica },
  { name: 'Elementos de mecánica de los fluidos', career: fisico_matematica },
  { name: 'Mecánica de los fluidos', career: fisico_matematica },
  { name: 'Métodos matemáticos aplicados a la Ingeniería Química', career: fisico_matematica },
  { name: 'Funciones de variable compleja', career: fisico_matematica },
  { name: 'Electromagnetismo', career: fisico_matematica },
  { name: 'Señales y sistemas', career: fisico_matematica },
  { name: 'Teoría de circuitos', career: fisico_matematica },
  { name: 'Electrotécnica', career: fisico_matematica },
  { name: 'Diseño Lógico', career: fisico_matematica },
  { name: 'Redes de datos 1', career: fisico_matematica },
  { name: 'Sistemas de control en tiempo discreto', career: fisico_matematica },
  { name: 'Análisis y control de sistemas no lineales', career: fisico_matematica },
  { name: 'Fundamentos de robótica industrial', career: fisico_matematica },
  { name: 'Matemática discreta 1', career: fisico_matematica },
  { name: 'Introducción a la Ciencia de Materiales', career: fisico_matematica },
  { name: 'Aplicaciones de álgebra lineal', career: fisico_matematica },
  { name: 'Señales aleatorias y modulación', career: fisico_matematica },
  { name: 'Transferencia de calor 2', career: fisico_matematica },
  { name: 'Energía 1 - Combustión', career: fisico_matematica },
  { name: 'Redes eléctricas', career: fisico_matematica },
  { name: 'Energía eólica y solar', career: fisico_matematica },
  { name: 'Hidrógeno', career: fisico_matematica },
  { name: 'Baterías', career: fisico_matematica },
  { name: 'Fundamentos de optimización', career: fisico_matematica },
  { name: 'Simulación de sistemas de energía eléctrica (SIMSEE)', career: fisico_matematica },
  { name: 'Transporte de energía eléctrica', career: fisico_matematica },
  { name: 'Fundamentos de aprendizaje automático', career: fisico_matematica },
  { name: 'Ciencia de datos', career: fisico_matematica },
  { name: 'Aprendizaje automático', career: fisico_matematica },
  { name: 'Minería de datos', career: fisico_matematica },
  { name: 'Big data', career: fisico_matematica },
  { name: 'Estadística', career: fisico_matematica },
  { name: 'Ciberseguridad', career: fisico_matematica },
  { name: 'Procesamiento de lenguaje natural', career: fisico_matematica },
  { name: 'Reconocimiento de imágenes', career: fisico_matematica },
  { name: 'Introducción al aprendizaje automático', career: fisico_matematica },
  { name: 'Fundamentos de aprendizaje automático y reconocimiento de patrones', career: fisico_matematica },
  { name: 'Estimación y predicción de series temporales', career: fisico_matematica },
  { name: 'Fundamentos de base de datos', career: fisico_matematica },
  { name: 'Teoría de grafos', career: fisico_matematica },
  { name: 'Teoría de la información', career: fisico_matematica },
  { name: 'Cálculo paralelo', career: fisico_matematica },
  { name: 'Lógica digital', career: fisico_matematica },
  { name: 'Robótica', career: fisico_matematica },
  { name: 'Procesamiento de señales', career: fisico_matematica },
  { name: 'Procesamiento digital de señales de audio', career: fisico_matematica },
  { name: 'Aprendizaje profundo para visión artificial', career: fisico_matematica },
  { name: 'Óptica de Fourier', career: fisico_matematica },
  { name: 'Física moderna', career: fisico_matematica },
  { name: 'Biología y biofísica básica', career: fisico_matematica },
  { name: 'Bioingeniería', career: fisico_matematica },
  { name: 'Control', career: fisico_matematica },
  { name: 'Electrónica Fundamental', career: fisico_matematica },
  { name: 'Medidas Eléctricas', career: fisico_matematica },
  { name: 'Física Experimental 3', career: fisico_matematica },
  { name: 'Introducción a la Física Moderna', career: fisico_matematica },
  { name: 'Física de los Dispositivos Electrónicos', career: fisico_matematica },
  { name: 'Física de los Dispositivos Semiconductores', career: fisico_matematica },
  { name: 'Fotónica', career: fisico_matematica },
  { name: 'Mecánica Estadística', career: fisico_matematica },
  { name: 'Mecánica Cuántica', career: fisico_matematica },
  { name: 'Física Computacional', career: fisico_matematica },
  { name: 'Métodos de Monte Carlo', career: fisico_matematica },
  { name: 'Modelos estadísticos para clasificación y regresión', career: fisico_matematica },
  { name: 'Electrónica Avanzada 2', career: fisico_matematica },
  { name: 'Diseño de Circuitos Integrados', career: fisico_matematica },
  { name: 'Introducción a los microprocesadores', career: fisico_matematica },
  { name: 'Sistemas Embebidos para Tiempo Real', career: fisico_matematica },
  { name: 'Vibraciones y ondas', career: fisico_matematica },
  { name: 'Óptica', career: fisico_matematica },
  { name: 'Análisis de Fourier para la Óptica clásica', career: fisico_matematica },
  { name: 'Imag. Óptica computacional', career: fisico_matematica },
  { name: 'Teoría Electromagnética', career: fisico_matematica },
  { name: 'Antenas y Propagación', career: fisico_matematica },
  { name: 'Propagación en Entornos Urbanos', career: fisico_matematica },
  { name: 'Sistemas de Comunicación', career: fisico_matematica },
  { name: 'Modelado y optimización', career: fisico_matematica },
  { name: 'Investigación operativa y gestión de riesgos', career: fisico_matematica },
  { name: 'Teoría, algoritmos y aplicaciones de gestión logística', career: fisico_matematica },
  { name: 'Optimización continua y aplicaciones', career: fisico_matematica },
  { name: 'Simulación a eventos discretos', career: fisico_matematica },
  { name: 'Introducción a los sistemas de información geográfica', career: fisico_matematica },
  { name: 'Taller de Aprendizaje Automático', career: fisico_matematica },
  { name: 'Ciencia, tecnología y sociedad', career: fisico_matematica },
  { name: 'Economía', career: fisico_matematica },
  { name: 'Administración de operaciones', career: fisico_matematica },
  { name: 'Costos para ingeniería', career: fisico_matematica },
  { name: 'Evaluación económica y financiera de proyectos de inversión', career: fisico_matematica },
  { name: 'Legislación y relaciones industriales', career: fisico_matematica },
  # Ing sistemas de comunicacion
  { name: 'Álgebra Lineal', career: ingsist },
  { name: 'Cálculo Diferencial e Integral', career: ingsist },
  { name: 'Ecuaciones Diferenciales', career: ingsist },
  { name: 'Probabilidad y Estadística', career: ingsist },
  { name: 'Transformadas Integrales', career: ingsist },
  { name: 'Funciones de Variable Compleja', career: ingsist },
  { name: 'Procesos Estocásticos', career: ingsist },
  { name: 'Física I', career: ingsist },
  { name: 'Física II', career: ingsist },
  { name: 'Electromagnetismo I', career: ingsist },
  { name: 'Electromagnetismo II', career: ingsist },
  { name: 'Termodinámica', career: ingsist },
  { name: 'Óptica', career: ingsist },
  { name: 'Física de los Dispositivos Semiconductores', career: ingsist },
  { name: 'Mecánica Newtoniana', career: ingsist },
  { name: 'Física Moderna', career: ingsist },
  { name: 'Física Cuántica', career: ingsist },
  { name: 'Química', career: ingsist },
  { name: 'Biología', career: ingsist },
  { name: 'Neurociencia', career: ingsist },
  { name: 'Teoría de Circuitos', career: ingsist },
  { name: 'Señales y Sistemas', career: ingsist },
  { name: 'Análisis de Fourier', career: ingsist },
  { name: 'Realimentación y Estabilidad', career: ingsist },
  { name: 'Sistemas Digitales I', career: ingsist },
  { name: 'Sistemas Digitales II', career: ingsist },
  { name: 'Arquitecturas de Computación de Alto Desempeño', career: ingsist },
  { name: 'Electrónica I', career: ingsist },
  { name: 'Electrónica II', career: ingsist },
  { name: 'Electrónica III', career: ingsist },
  { name: 'Fundamentos de los Sistemas de Comunicación', career: ingsist },
  { name: 'Teoría de la Información', career: ingsist },
  { name: 'Filtros Digitales', career: ingsist },
  { name: 'Modelado y Procesamiento del Ruido en Canales de Comunicación', career: ingsist },
  { name: 'Introducción a la Programación', career: ingsist },
  { name: 'Estructuras de Datos', career: ingsist },
  { name: 'Programación en Lenguajes Cercanos al Hardware', career: ingsist },
  { name: 'Programación Orientada a Objetos', career: ingsist },
  { name: 'Programación para Cálculo Científico', career: ingsist },
  { name: 'Análisis de Algoritmos', career: ingsist },
  { name: 'Modulación Analógica y Digital', career: ingsist },
  { name: 'Diseño de Receptores y Transmisores', career: ingsist },
  { name: 'Redes de Datos', career: ingsist },
  { name: 'Antenas y Propagación', career: ingsist },
  { name: 'Corrección de Errores', career: ingsist },
  { name: 'Arquitectura de Servicios de Telecomunicaciones', career: ingsist },
  { name: 'Desarrollo de Servicios sobre Redes de Comunicaciones', career: ingsist },
  { name: 'Encriptado', career: ingsist },
  { name: 'Sistemas Operativos', career: ingsist },
  { name: 'Bases de Datos', career: ingsist },
  { name: 'Diseño de Software', career: ingsist },
  { name: 'Investigación Operativa', career: ingsist },
  { name: 'Diseño de Sistemas con FPGA', career: ingsist },
  { name: 'Circuitos de Radio Frecuencia', career: ingsist },
  { name: 'Sistemas Embebidos', career: ingsist },
  { name: 'Sistemas Basados en Microcontroladores', career: ingsist },
  { name: 'Diseño de Circuitos Integrados', career: ingsist },
  { name: 'Reconocimiento de Patrones o Aprendizaje Automático', career: ingsist },
  { name: 'Tratamiento Estadístico de Señales', career: ingsist },
  { name: 'Procesamiento de Grandes Volúmenes de Información (Big Data)', career: ingsist },
  { name: 'Procesamiento de Imágenes, Audio y Video', career: ingsist },
  { name: 'Detección y Decisión', career: ingsist },
  { name: 'Proyecto de Fin de Carrera', career: ingsist },
  { name: 'Pasantías', career: ingsist },
  { name: 'Talleres', career: ingsist },
  { name: 'Legislación y Relaciones Industriales', career: ingsist },
  { name: 'Higiene y Seguridad Industrial', career: ingsist },
  { name: 'Costos y Administración', career: ingsist },
  { name: 'Gestión Empresarial', career: ingsist },
  { name: 'Gestión de Calidad', career: ingsist },
  { name: 'Implicancias Sociales y Ambientales de la Tecnología', career: ingsist },
  { name: 'Sociología', career: ingsist },
  { name: 'Economía', career: ingsist },
  # Ing Agrimensura
  { name: 'Álgebra lineal', career: agrimensura },
  { name: 'Cálculo diferencial e integral en una y varias variables', career: agrimensura },
  { name: 'Probabilidad, estadística y geoestadística', career: agrimensura },
  { name: 'Sistemas de referencia', career: agrimensura },
  { name: 'Cartografía matemática', career: agrimensura },
  { name: 'Mecánica de partículas y sistemas sencillos', career: agrimensura },
  { name: 'Ondas electromagnéticas', career: agrimensura },
  { name: 'Óptica', career: agrimensura },
  { name: 'Física moderna', career: agrimensura },
  { name: 'Física de la Tierra', career: agrimensura },
  { name: 'Derecho básico', career: agrimensura },
  { name: 'Economía', career: agrimensura },
  { name: 'Sociología', career: agrimensura },
  { name: 'Programación básica', career: agrimensura },
  { name: 'Cálculo computacional', career: agrimensura },
  { name: 'Ajustes de observaciones', career: agrimensura },
  { name: 'Aplicación de técnicas de ajuste', career: agrimensura },
  { name: 'Pre-análisis de errores', career: agrimensura },
  { name: 'Calidad de la información', career: agrimensura },
  { name: 'Bienes, propiedad o dominio, modos de adquirir el dominio', career: agrimensura },
  { name: 'Limitaciones al derecho de propiedad', career: agrimensura },
  { name: 'Fraccionamiento de la tierra urbana y rural', career: agrimensura },
  { name: 'Régimen de propiedad horizontal y normas de división por este régimen', career: agrimensura },
  { name: 'Expropiaciones', career: agrimensura },
  { name: 'Metodologías avaluatorias aplicables a la valoración inmobiliaria', career: agrimensura },
  { name: 'Avalúo de inmuebles urbanos y rurales', career: agrimensura },
  { name: 'Avalúo de inmuebles en régimen común y propiedad horizontal', career: agrimensura },
  { name: 'Avalúos especiales sobre derechos reales', career: agrimensura },
  { name: 'Avalúos con fines expropiatorios', career: agrimensura },
  { name: 'Catastro en el Uruguay', career: agrimensura },
  { name: 'Catastros multifinalitarios', career: agrimensura },
  { name: 'Vinculación entre el catastro y el registro de la propiedad inmueble', career: agrimensura },
  { name: 'Geodesia Física', career: agrimensura },
  { name: 'Geodesia Geométrica', career: agrimensura },
  { name: 'Astronomía Geodésica', career: agrimensura },
  { name: 'Geodesia Espacial', career: agrimensura },
  { name: 'Cartografía matemática', career: agrimensura },
  { name: 'Teledetección', career: agrimensura },
  { name: 'Fotogrametría', career: agrimensura },
  { name: 'Relevamientos masivos de datos', career: agrimensura },
  { name: 'Sistemas de información geográfica', career: agrimensura },
  { name: 'Planificación territorial', career: agrimensura },
  { name: 'Normativa nacional y departamental sobre ordenamiento territorial y desarrollo sostenible', career: agrimensura },
  { name: 'Instrumentos de ordenamiento territorial', career: agrimensura },
  { name: 'Manejo de instrumental topográfico', career: agrimensura },
  { name: 'Errores y control del instrumental topográfico', career: agrimensura },
  { name: 'Sensibilidad de métodos de relevamiento topográfico y replanteo', career: agrimensura },
  { name: 'Nociones básicas de sociología y ética', career: agrimensura },
  { name: 'Aspectos sobre filosofía de la ciencia', career: agrimensura },
  { name: 'Aspectos legales y éticos del ejercicio profesional', career: agrimensura },
  { name: 'Gestión de proyectos', career: agrimensura },
  { name: 'Nociones básicas sobre el funcionamiento de las organizaciones', career: agrimensura },
  { name: 'Gestión de las organizaciones', career: agrimensura },
  { name: 'Proyecto', career: agrimensura },
  { name: 'Pasantía', career: agrimensura },
  # Ing Electrica
  { name: 'Álgebra lineal', career: electrica },
  { name: 'Cálculo diferencial e integral en una y varias variables', career: electrica },
  { name: 'Ecuaciones diferenciales', career: electrica },
  { name: 'Probabilidad y estadística', career: electrica },
  { name: 'Transformadas integrales', career: electrica },
  { name: 'Funciones de variable compleja', career: electrica },
  { name: 'Cálculo numérico', career: electrica },
  { name: 'Magnitudes y propagación de errores', career: electrica },
  { name: 'Cinemática y dinámica', career: electrica },
  { name: 'Estática y dinámica de partículas', career: electrica },
  { name: 'Vibraciones y ondas', career: electrica },
  { name: 'Electrostática y magnetostática', career: electrica },
  { name: 'Termodinámica', career: electrica },
  { name: 'Mecánica Newtoniana', career: electrica },
  { name: 'Ecuaciones de Maxwell y ondas electromagnéticas', career: electrica },
  { name: 'Óptica', career: electrica },
  { name: 'Física de los dispositivos semiconductores', career: electrica },
  { name: 'Física Moderna', career: electrica },
  { name: 'Física Cuántica', career: electrica },
  { name: 'Química', career: electrica },
  { name: 'Biología', career: electrica },
  { name: 'Neurociencia', career: electrica },
  { name: 'Teoría de circuitos', career: electrica },
  { name: 'Realimentación y estabilidad', career: electrica },
  { name: 'Análisis de Fourier de señales en tiempo continuo y discreto', career: electrica },
  { name: 'Muestreo y procesamiento digital', career: electrica },
  { name: 'Señales y sistemas', career: electrica },
  { name: 'Introducción a las medidas eléctricas', career: electrica },
  { name: 'Fundamentos del análisis y síntesis de circuitos combinatorios y secuenciales', career: electrica },
  { name: 'Modelos de los dispositivos electrónicos elementales: diodo, transistor', career: electrica },
  { name: 'Aplicación de estos dispositivos a funciones analógicas y digitales', career: electrica },
  { name: 'Amplificadores operacionales', career: electrica },
  { name: 'Fundamentos de los sistemas de comunicación', career: electrica },
  { name: 'Modelado y procesamiento del ruido', career: electrica },
  { name: 'Fundamentos de máquinas eléctricas rotativas', career: electrica },
  { name: 'Fundamentos sobre Transformadores', career: electrica },
  { name: 'Fundamentos de programación', career: electrica },
  { name: 'Estructuras de datos', career: electrica },
  { name: 'Física Aplicada', career: electrica },
  { name: 'Matemática aplicada', career: electrica },
  { name: 'Modelado de sistemas de control', career: electrica },
  { name: 'Análisis y síntesis de sistemas de control realimentado', career: electrica },
  { name: 'Control óptimo', career: electrica },
  { name: 'Control no lineal', career: electrica },
  { name: 'Aplicaciones de control', career: electrica },
  { name: 'Máquinas eléctricas rotativas', career: electrica },
  { name: 'Transformadores', career: electrica },
  { name: 'Convertidores estáticos de potencia', career: electrica },
  { name: 'Control de máquinas eléctricas', career: electrica },
  { name: 'Programación en lenguajes para aplicaciones cercanas al hardware', career: electrica },
  { name: 'Programación orientada a objetos', career: electrica },
  { name: 'Programación para cálculo científico', career: electrica },
  { name: 'Análisis de algoritmos', career: electrica },
  { name: 'Sistemas operativos', career: electrica },
  { name: 'Bases de datos', career: electrica },
  { name: 'Diseño de software', career: electrica },
  { name: 'Investigación operativa', career: electrica },
  { name: 'Instalaciones eléctricas', career: electrica },
  { name: 'Redes eléctricas', career: electrica },
  { name: 'Transmisión de energía eléctrica', career: electrica },
  { name: 'Medidas y protecciones en sistemas eléctricos de potencia', career: electrica },
  { name: 'Distribución de energía eléctrica', career: electrica },
  { name: 'Generación de energía eléctrica', career: electrica },
  { name: 'Modelos de los dispositivos electrónicos elementales: diodo, transistor bipolar, transistor de efecto de campo', career: electrica },
  { name: 'Aplicación de estos dispositivos a funciones de amplificación y generación de formas de onda', career: electrica },
  { name: 'Aspectos eléctricos de los circuitos integrados analógicos y digitales: modelo de amplificadores operacionales y familias lógicas', career: electrica },
  { name: 'Diseño de circuitos integrados', career: electrica },
  { name: 'Análisis, diseño y técnicas de implementación de circuitos combinatorios y secuenciales', career: electrica },
  { name: 'Operación, arquitectura y software de base de sistemas basados en microprocesador (de propósito general o embebidos)', career: electrica },
  { name: 'Dispositivos de electrónica digital, lógica programable y sistemas basados en ellos', career: electrica },
  { name: 'Sistemas de comunicación', career: electrica },
  { name: 'Redes de datos', career: electrica },
  { name: 'Modulación analógica y digital', career: electrica },
  { name: 'Diseño de receptores y transmisores', career: electrica },
  { name: 'Antenas y propagación', career: electrica },
  { name: 'Arquitectura de servicios de telecomunicaciones', career: electrica },
  { name: 'Desarrollo de servicios sobre redes de comunicaciones', career: electrica },
  { name: 'Redes ópticas', career: electrica },
  { name: 'Redes inalámbricas', career: electrica },
  { name: 'Teoría de la Información', career: electrica },
  { name: 'Encriptado', career: electrica },
  { name: 'Modelado, análisis, diseño y estudio del desempeño de los diferentes sistemas de comunicaciones', career: electrica },
  { name: 'Modelado estocástico de señales', career: electrica },
  { name: 'Reconocimiento de patrones o aprendizaje automático', career: electrica },
  { name: 'Procesamiento estadístico de señales', career: electrica },
  { name: 'Procesamiento de grandes volúmenes de información', career: electrica },
  { name: 'Procesamiento de imágenes, audio y video', career: electrica },
  { name: 'Detección y decisión', career: electrica },
  { name: 'Proyectos', career: electrica },
  { name: 'Pasantías', career: electrica },
  { name: 'Talleres', career: electrica },
  # Ing Produccion
  { name: 'Cálculo 1', career: produccion },
  { name: 'Cálculo 2', career: produccion },
  { name: 'Cálculo 3', career: produccion },
  { name: 'Geometría y Álgebra 1', career: produccion },
  { name: 'Geometría y Álgebra 2', career: produccion },
  { name: 'Probabilidad y Estadística', career: produccion },
  { name: 'Ecuaciones Diferenciales', career: produccion },
  { name: 'Física 1', career: produccion },
  { name: 'Física 2', career: produccion },
  { name: 'Física 3', career: produccion },
  { name: 'Laboratorio 1', career: produccion },
  { name: 'Laboratorio 2', career: produccion },
  { name: 'Física Térmica', career: produccion },
  { name: 'Mecánica Newtoniana', career: produccion },
  { name: 'Principios de Química General', career: produccion },
  { name: 'Materiales y Ensayos', career: produccion },
  { name: 'Programación 1', career: produccion },
  { name: 'Métodos Numéricos', career: produccion },
  { name: 'Transferencia de Calor 1', career: produccion },
  { name: 'Transferencia de Calor 2', career: produccion },
  { name: 'Estática Aplicada', career: produccion },
  { name: 'Estática de Sólidos Deformables', career: produccion },
  { name: 'Operaciones', career: produccion },
  { name: 'Introducción a la Investigación de Operaciones', career: produccion },
  { name: 'Gestión de Calidad y Productividad', career: produccion },
  { name: 'Desarrollo de Productos', career: produccion },
  { name: 'Gestión de Operaciones', career: produccion },
  { name: 'Administración de Empresas', career: produccion },
  { name: 'Microeconomía', career: produccion },
  { name: 'Organizaciones y su Administración', career: produccion },
  { name: 'Derecho Laboral', career: produccion },
  { name: 'Higiene y Seguridad Laboral', career: produccion },
  { name: 'Responsabilidad Social Empresarial', career: produccion },
  { name: 'Tecnología y Sociedad', career: produccion },
  { name: 'Economía', career: produccion },
  { name: 'Electrotecnia 1', career: produccion },
  { name: 'Introducción al Control', career: produccion },
  { name: 'Control e Instrumentación Industrial', career: produccion },
  { name: 'Introducción a la Ingeniería Química', career: produccion },
  { name: 'Elementos de Ingeniería Ambiental', career: produccion },
  { name: 'Servicios Industriales', career: produccion },
  { name: 'Bases de Datos y Sistemas de Información', career: produccion },
  { name: 'Pasantía', career: produccion },
  { name: 'Proyecto', career: produccion },
  # Ing Alimentos
  { name: 'Cálculo Diferencial e Integral en una Variable', career: alimentos },
  { name: 'Cálculo Diferencial e Integral en Varias Variables', career: alimentos },
  { name: 'Geometría y Álgebra Lineal 1', career: alimentos },
  { name: 'Geometría y Álgebra Lineal 2', career: alimentos },
  { name: 'Física 1', career: alimentos },
  { name: 'Física 2', career: alimentos },
  { name: 'Química General 1', career: alimentos },
  { name: 'Química General 2', career: alimentos },
  { name: 'Prevención de Riesgos en el Laboratorio', career: alimentos },
  { name: 'Economía', career: alimentos },
  { name: 'Introducción a las Ciencias Biológicas 1', career: alimentos },
  { name: 'Cálculo Vectorial', career: alimentos },
  { name: 'Química Orgánica 102', career: alimentos },
  { name: 'Física 3', career: alimentos },
  { name: 'Química Analítica 2', career: alimentos },
  { name: 'Probabilidad y Estadística', career: alimentos },
  { name: 'Fisicoquímica 101', career: alimentos },
  { name: 'Matemática 06', career: alimentos },
  { name: 'Introducción a las Ecuaciones Diferenciales', career: alimentos },
  { name: 'Química Orgánica 101', career: alimentos },
  { name: 'Introducción a la Ingeniería Química y de Procesos', career: alimentos },
  { name: 'Química Analítica 1', career: alimentos },
  { name: 'Matemática 01', career: alimentos },
  { name: 'Matemática 04', career: alimentos },
  { name: 'Matemática 03', career: alimentos },
  { name: 'Física 101', career: alimentos },
  { name: 'Física 102', career: alimentos },
  { name: 'Matemática 05', career: alimentos },
  { name: 'Matemática 07', career: alimentos },
  { name: 'Física 103 (Laboratorio)', career: alimentos },
  { name: 'Fisicoquímica 103', career: alimentos },
  { name: 'Fluidodinámica', career: alimentos },
  { name: 'Química Orgánica 103 (Laboratorio)', career: alimentos },
  { name: 'Transferencia de Calor y Masa 1', career: alimentos },
  { name: 'Fenómenos de Transporte en Ingeniería de Procesos', career: alimentos },
  { name: 'Microbiología General', career: alimentos },
  { name: 'Termodinámica Aplicada a Ingeniería de Procesos', career: alimentos },
  { name: 'Química de Alimentos', career: alimentos },
  { name: 'Física Experimental 1', career: alimentos },
  { name: 'Bioquímica (Opción 1)', career: alimentos },
  { name: 'Bioquímica (Opción 2)', career: alimentos },
  { name: 'Bioquímica (Opción 3)', career: alimentos },
  { name: 'Ingeniería de las Reacciones Químicas 1', career: alimentos },
  { name: 'Control de Calidad', career: alimentos },
  { name: 'Microbiología Alimentaria', career: alimentos },
  { name: 'Nutrición Aplicada a la Ingeniería de Alimentos', career: alimentos },
  { name: 'Alimentos y Procesos Salud-Enfermedad', career: alimentos },
  { name: 'Transferencia de Calor y Masa 2', career: alimentos },
  { name: 'Análisis de Alimentos', career: alimentos },
  { name: 'Higiene y Seguridad de Alimentos', career: alimentos },
  { name: 'Laboratorio de Química de Alimentos', career: alimentos },
  { name: 'Toxicología Alimentaria', career: alimentos },
  { name: 'Higiene y Servicios de Plantas Procesadoras de Alimentos', career: alimentos },
  { name: 'Pasantía-Trabajo Práctico de Grado (Módulo 1)', career: alimentos },
  { name: 'Proyecto Industrial 2', career: alimentos },
  { name: 'Proyecto Industrial 1', career: alimentos },
  { name: 'Legislación Alimentaria', career: alimentos },
  { name: 'Gestión de Calidad', career: alimentos },
  { name: 'Gestión de los Procesos en la Industria', career: alimentos },
  { name: 'Ingeniería Bioquímica', career: alimentos },
  # Ing Civil
  { name: 'Cálculo Diferencial e Integral en una Variable', career: civil },
  { name: 'Geometría Analítica', career: civil },
  { name: 'Álgebra Lineal', career: civil },
  { name: 'Física 1', career: civil },
  { name: 'Química', career: civil },
  { name: 'Introducción a la Ingeniería 1', career: civil },
  { name: 'Cálculo Diferencial e Integral en Varias Variables', career: civil },
  { name: 'Geometría y Álgebra Lineal 2', career: civil },
  { name: 'Física 2', career: civil },
  { name: 'Probabilidad y Estadística', career: civil },
  { name: 'Expresión Gráfica', career: civil },
  { name: 'Computación 1', career: civil },
  { name: 'Ingeniería Legal', career: civil },
  { name: 'Ecuaciones Diferenciales', career: civil },
  { name: 'Resistencia de Materiales 1', career: civil },
  { name: 'Mecánica Newtoniana', career: civil },
  { name: 'Materiales y Ensayos', career: civil },
  { name: 'Ciencia, Tecnología y Sociedad', career: civil },
  { name: 'Elementos de Mecánica de los Fluidos', career: civil },
  { name: 'Geodesia', career: civil },
  { name: 'Resistencia de Materiales 2', career: civil },
  { name: 'Hidráulica e Hidrología Aplicada', career: civil },
  { name: 'Topografía', career: civil },
  { name: 'Tecnología de la Construcción', career: civil },
  { name: 'Hormigón Estructural 1', career: civil },
  { name: 'Introducción a la Ingeniería de Suelos', career: civil },
  { name: 'Caminos y Ferrocarriles 1', career: civil },
  { name: 'Hormigón Estructural 2', career: civil },
  { name: 'Procedimientos de Construcción para Obras Viales y Estructuras', career: civil },
  { name: 'Métodos Computacionales Aplicados al Cálculo Estructural', career: civil },
  { name: 'Estructuras de Acero', career: civil },
  { name: 'Introducción al Transporte', career: civil },
  { name: 'Sanitaria', career: civil },
  { name: 'Laboratorio de Resistencia de Materiales 1', career: civil },
  { name: 'Proyectos, Planificación y Gestión de Obra 1', career: civil },
  { name: 'Laboratorio de Transporte', career: civil },
  { name: 'Economía A', career: civil },
  { name: 'Representación Gráfica - Módulo "B"', career: civil },
  { name: 'Ingeniería Gráfica e Hidráulica Aplicada', career: civil },
  { name: 'Caminos 2', career: civil },
  { name: 'Legislación General para Ingenieros', career: civil },
  { name: 'Introducción a la Gestión', career: civil },
  { name: 'Caminos 3', career: civil },
  { name: 'Planificación y Programación', career: civil },
  { name: 'Introducción a la Ingeniería Sanitaria 1', career: civil },
  { name: 'Laboratorio de Caminos 1', career: civil },
  { name: 'Seguridad en la Construcción', career: civil },
  { name: 'Materiales de la Construcción', career: civil },
  { name: 'Hidráulica Aplicada', career: civil },
  { name: 'Introducción a la Ingeniería Ambiental', career: civil },
  { name: 'Hidráulica Fluvial', career: civil },
  { name: 'Abastecimiento de Agua Potable y Alcantarillado (A+A)', career: civil },
  { name: 'Diseño Hidráulico de Obras Civiles', career: civil },
  { name: 'Hidrología General', career: civil },
  { name: 'Ingeniería de Ríos', career: civil },
  { name: 'Tratamiento de Efluentes Líquidos', career: civil },
  { name: 'Proyecto Hidráulico-Ambiental', career: civil },
  { name: 'Mecánica de Suelos', career: civil },
  { name: 'Gestión Ambiental', career: civil },
  # Ing Computacion
  { name: 'Matemática Inicial', career: ingcomp },
  { name: 'Matemática Discreta 1', career: ingcomp },
  { name: 'Cálculo Diferencial e Integral en Una Variable', career: ingcomp },
  { name: 'Física 1', career: ingcomp },
  { name: 'Geometría y Álgebra Lineal 1', career: ingcomp },
  { name: 'Cálculo Diferencial e Integral en Varias Variables', career: ingcomp },
  { name: 'Geometría y Álgebra Lineal 2', career: ingcomp },
  { name: 'Lógica', career: ingcomp },
  { name: 'Matemática Discreta 2', career: ingcomp },
  { name: 'Arquitectura de Computadoras', career: ingcomp },
  { name: 'Probabilidad y Estadística', career: ingcomp },
  { name: 'Métodos Numéricos', career: ingcomp },
  { name: 'Introducción a la Investigación Operativa', career: ingcomp },
  { name: 'Sistemas Operativos', career: ingcomp },
  { name: 'Teoría de Lenguajes', career: ingcomp },
  { name: 'Fundamentos de Bases de Datos', career: ingcomp },
  { name: 'Taller de Programación', career: ingcomp },
  { name: 'Redes de Computadoras', career: ingcomp },
  { name: 'Introducción a la Ing de Soft.', career: ingcomp },
  { name: 'Prog. Funcional o Prog. Lógica', career: ingcomp },
  { name: 'Administración General para Ingenieros (*)', career: ingcomp },
  { name: 'Proyecto de Ingeniería de Software', career: ingcomp },
  { name: 'Economía (*)', career: ingcomp },
  { name: 'Práctica de Administración para Ingenieros (*)', career: ingcomp },
  { name: 'Polítias Científicas en Inf. y Comp. (*)', career: ingcomp }
]

subjects.each do |subject|
  Subject.find_or_create_by!({ name: subject[:name], career: subject[:career] })
end

# Creo dos usuarios tutores, este va a tener asociados temas (disponibilidades)
user_1 = User.find_or_create_by!({
  name: "John Doe",
  email: "john.doe@example.com",
  uid: "123456789",
  description: "Tutor especializado en matemáticas.",
  image_url: "https://i.pinimg.com/550x/74/bb/34/74bb340ffe87e31837a04a538f1bbc10.jpg",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
  }
)

user_2 = User.find_or_initialize_by(email: "jane.doe@example.com")
user_2.assign_attributes({
  name: "Jane Doe",
  uid: "123451789",
  description: "Tutor especializado en algo.",
  image_url: "https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
  }
)
user_2.save!
# Este usuario va a ser estudiante
user_3 = User.find_or_create_by!({
  name: "Juan Pablo",
  email: "juan.pablo@example.com",
  uid: "123456782",
  description: "Estudiante.",
  image_url: "https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png",
  ranking: 0,
  amount_given_lessons: 0,
  amount_given_topics: 0,
  amount_attended_students: 0,
  attended_lessons: 0,
  attended_tutors: 0,
  attended_topics: 0
})

programacion1_id = Subject.find_by(name: "Programación 1").id
logica_id = Subject.find_by(name: "Lógica").id
# Topics Creation
# Programación 1 - subject_id = 1
begin
Topic.find_or_create_by!([
  { name: "Introducción a la Programación", description: "Conceptos básicos de programación.", subject_id: programacion1_id },
  { name: "Estructuras de Control", description: "Condicionales y bucles.", subject_id: programacion1_id },
  { name: "Funciones", description: "Cómo escribir funciones y modularizar código.", subject_id: programacion1_id },
  { name: "Manejo de Errores", description: "Técnicas para el manejo de errores en programación.", subject_id: programacion1_id },
  { name: "Programación Orientada a Objetos", description: "Fundamentos de POO.", subject_id: programacion1_id }
])
rescue
end

# Lógica - subject_id = 5
Topic.find_or_create_by!([
  { name: "Proposiciones Lógicas", description: "Introducción a la lógica proposicional.", subject_id: logica_id },
  { name: "Tablas de Verdad", description: "Uso de tablas de verdad para evaluar expresiones.", subject_id: logica_id },
  { name: "Tautologías y Contradicciones", description: "Estudio de tautologías y contradicciones lógicas.", subject_id: logica_id },
  { name: "Lógica de Predicados", description: "Introducción a la lógica de predicados.", subject_id: logica_id },
  { name: "Cuantificadores", description: "Cuantificadores existenciales y universales.", subject_id: logica_id }
])

# Creation of Availabilities for two topics of subject_1 for the user created
topics = Topic.where(subject_id: programacion1_id)
topics.each do |topic|
  AvailabilityTutor.find_or_create_by!({
    user_id: user_1.id,
    topic_id: topic.id
})
end

topics = Topic.where(subject_id: logica_id)
topics.each do |topic|
  availability = AvailabilityTutor.find_or_create_by!({
    user_id: user_2.id,
    topic_id: topic.id
  })
end
